完成concepts/usb/overview.md的翻译
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #102
Opened 2021-07-25 16:14 UTC by luminouser

2021-07-26 16:01 UTC, chuyao commented on concepts/usb/overview.md
> +Zircon提供了一个功能完备的USB子系统，它能够使您开发USB主设备（USB host）
`您` 字用的有点重了，一般要用的话，用 `你` 就够了

2021-07-26 16:28 UTC, chuyao requested changes
整体翻译还算通顺，但格式需要修改，需要遵循 [文档翻译规则](https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN#%E6%96%87%E6%A1%A3%E7%9A%84%E6%9E%84%E6%88%90) ，同时，有些 Markdown 语法的问题，希望能多看看 Markdown 的语法表述。

2021-07-26 16:28 UTC, chuyao commented on concepts/usb/overview.md
> +集线器驱动的目的是根据《USB 2.0规格（USB 2.0 spec）》中的第11章来
[USB 2.0 specification][USB 2.0 spec] 应翻译作 [USB 2.0 规格][USB 2.0 spec]，Markdown链接需要保留

2021-07-26 16:28 UTC, chuyao commented on concepts/usb/overview.md
> +要获取关于集线器生命周期的细节的信息，参考[USB 2.0 规格]的第11章。
同上边的 Markdown 链接翻译问题

2021-07-26 16:28 UTC, chuyao commented on concepts/usb/overview.md
> +存在于USB协议栈的底层。它负责将尚未处理的“usb_request_t”翻译成必要的、能够
`usb_request_t` 需要原样保留，无需以引号代替，详见 Markdown 语法。

2021-07-26 16:28 UTC, chuyao commented on concepts/usb/overview.md
> +- 总线枚举（通过“set_address”命令来做到）。
`set_address` 也要原样保留

2021-07-26 16:28 UTC, chuyao commented on concepts/usb/overview.md
> +驱动存在于USB协议栈的底层。它负责将尚未处理的“usb_request_t”翻译成必要的、能够
`translating` 翻译成 `转换` 可能要恰当一些

2021-07-26 16:28 UTC, chuyao commented on concepts/usb/overview.md
>  [USB 2.0 spec]: https://www.usb.org/document-library/usb-20-specification
这里应该只留一个，同时需要注意上边文章中对链接的引用，比如第139行

2021-07-27 07:20 UTC, luminouser commented on concepts/usb/overview.md
> +Zircon提供了一个功能完备的USB子系统，它能够使您开发USB主设备（USB host）
抱歉，当乙方当惯了，“您”成了我的习惯性用语

2021-08-15 02:45 UTC, y2-Whyto commented on concepts/usb/overview.md
> +Zircon提供了一个功能完备的USB子系统，它能够使您开发USB主设备（USB host）
> `您` 字用的有点重了，一般要用的话，用 `你` 就够了

统一起见都用“您”比较好吧，文档作为服务开发者的工具资料，用“您”可能更好些。

此外，Google的文档使用的也是“您”。

2021-08-23 16:19 UTC, luminouser commented
根据要求更新了译文。

2021-08-27 16:18 UTC, chuyao requested changes
一些Markdown格式的小问题仍需要注意，继续加油！ @luminouser

2021-08-27 16:18 UTC, chuyao commented on concepts/usb/overview.md
> +驱动存在于USB协议栈的底层。它负责将尚未处理的“usb_request_t”转变成必要的、能够
Markdown 的代码符号不能随意修改，`usb_request_t` ，不是双引号

2021-08-27 16:18 UTC, chuyao commented on concepts/usb/overview.md
> +一般而言，USB设备的驱动将数据传输请求编码成一个“usb_request_t”结构体。这些
Markdown 代码符号不能用双引号代替。保留原格式 `usb_request_t` 即可。

2021-10-17 14:42 UTC, merged