Translated /concepts/prebuilt_packages/
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #105
Opened 2021-08-04 04:57 UTC by y2-Whyto

2021-08-04 17:08 UTC, chuyao requested changes

2021-08-04 17:08 UTC, chuyao commented on concepts/prebuilt_packages/prebuilt_cipd_packages_in_fuchsia.md
>  # Prebuilt CIPD packages in Fuchsia
这个大标题忘了注释了吧

2021-08-05 10:27 UTC, y2-Whyto commented on concepts/prebuilt_packages/prebuilt_cipd_packages_in_fuchsia.md
>  # Prebuilt CIPD packages in Fuchsia
感谢提醒，已修复。

2021-08-05 10:28 UTC, y2-Whyto commented on concepts/prebuilt_packages/prebuilt_cipd_packages_in_fuchsia.md
>  # Prebuilt CIPD packages in Fuchsia
> 这个大标题忘了注释了吧

感谢提醒，已修复。

2021-08-05 13:53 UTC, chuyao approved these changes

2021-08-05 13:56 UTC, merged