translate testing.md
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #110
Opened 2021-08-22 15:38 UTC by chuyao

translate testing.md

2021-08-26 10:20 UTC, y2-Whyto requested changes
我做了如下校对，烦请您费心查看，稍作斟酌。如有异议，可以再议。

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +本文档描述了为 Rust 代码编写测试的最佳实践。
```suggestion
本文档描述了为 Rust 代码编写测试的最佳做法。
```
根据 Issue 表决结果，请使用“最佳做法”这一翻译方法，以便统一。

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +也请参考[组件测试指南][component_tests]中关于定义测试包和组件的介绍，并运行它们。
这里的defining和running是并列关系，instructions是关于这两者的，烦请重新斟酌一下翻译。

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +本文档面向的是在`fuchsia.git`中工作的开发人员，对工作流的描述不太可能适用于IDK消费者。
```suggestion
本文档面向的是在`fuchsia.git`中工作的开发人员，对工作流的描述不太可能适用于 IDK 消费者。
```
少了空格。另外，目测这里IDK应该就是I-don't-know，IDK consumer应该是说“啥也不知道的消费者”。可以再做查询（我没有谷歌到IDK consumer的任何有用信息）。

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +本教程的源代码可以在[`//examples/hello_world/rust`][example-src]中找到
```suggestion
本教程的源代码可以在[`//examples/hello_world/rust`][example-src]中找到。
```

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +这会生成一个新的、命名为 `tests` 的 mod， 这个 mod 仅在构建单元测试的时候能被包含。任何带有 `#[test]` 注解的方法都会被当成一个测试来运行，如果方法成功返回，就意味着测试通过。
```suggestion
这会生成一个新的、命名为 `tests` 的 mod， 这个 mod 将仅在构建单元测试的时候被包含。任何带有 `#[test]` 注解的方法都会被当成一个测试来运行，如果方法成功返回，就意味着测试通过。
```
“将”似乎不该替换成“能”。

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +为了练习测试异步代码，在使用异步执行器的时候，使用 `#[fasync::run_until_stalled(test)]` 注解是一个选项。
```suggestion
对于异步代码的测试，在使用异步执行器的时候，可以选择使用 `#[fasync::run_until_stalled(test)]` 注解。
```
这里exercising是test的定语，直译就是“对于测试异步代码的测试”，有赘余，可以删去前一个“测试”。后半句主系表结构翻译成动宾结构或许会更通顺一些？

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +单元测试可以由 Rust targets 自动生成（例如，`rustc_binary` 或者 `rustc_library`）。这些方法大体上是相似的。
```suggestion
单元测试可以由 Rust 目标自动生成（即 `rustc_binary` 或者 `rustc_library`）。这些方法大体上是相似的。
```
targets应该可以直接翻译？“i.e.”是即（that is）。

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +#### 为 Rust binary 构建测试
binary应该也可以直接翻译为“二进制”？这个应该没什么歧义，当然要想体现原文也可以加括号。（只是个人建议，下同）

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +如果你正在测试一个 rust *binary* （例如，你有一个 `main.rs`），这个章节会对你很有用。如果你是在测试 library ，请看下一章节
```suggestion
如果你正在测试一个 rust *二进制* （例如，你有一个 `main.rs`），这个章节会对你很有用。如果你是在测试库 ，请看下一章节
```
binary 可以直接翻译成“二进制”，library 应当翻译吧

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +单元测试只有在设置中加入了 `with_unit_tests = true` 才能被 `rustc_binary` GN 模板构建：
```suggestion
只有在设置中加入了 `with_unit_tests = true` 时，单元测试才能被 `rustc_binary` GN 模板构建：
```
在……时

调换一下顺序可能更好理解？

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +#### 为 Rust library 构建测试
```suggestion
#### 为 Rust 库构建测试
```

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +你的 `BUILD.gn` 文件首先需要通过引用 `rust_binary` 模板来使其可用：
```suggestion
你的 `BUILD.gn` 文件首先需要通过导入 `rust_binary` 模板来使其可用：
```
import 导入？

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +你的 `BUILD.gn` 文件首先需要通过引用 `rust_library` 模板来使其可用：
```suggestion
你的 `BUILD.gn` 文件首先需要通过导入 `rust_library` 模板来使其可用：
```
同 Line 112

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +单元测试只有在设置中加入了 `with_unit_tests = true` 才能被 `rustc_library` GN 模板构建，和上边 `rustc_binary` 例子一样。
```suggestion
只有在设置中加入了 `with_unit_tests = true` 时，单元测试才能被 `rustc_library` GN 模板构建，和上边 `rustc_binary` 例子一样。
```
和上边 `rustc_binary` 例子一样。（Line 116）

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +在这个示例中，当然，一个 `不同命名` 的测试二进制程序会被生成：
```suggestion
然而在这个示例中，会生成一个**名称不同**的二进制测试程序：
```
however 然而。differently named 格式似乎错了。被动译成主动更通顺一些。

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +#### 书写包清单
```suggestion
#### 编写包清单
```
用“编写”可能会好一些？

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +一个包清单目前是必要的。清单位于 `meta/` 子目录下，即包含你的 `BUILD.gn` 文件的目录下。
```suggestion
一个包清单目前是必要的。清单位于 `meta/` 子目录下，直接位于包含你 `BUILD.gn` 文件的目录下。
```
immediately == directly，直接，就是不能隔目录。

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +一个最简清单如下所示，并且 **必须** 和上边的由 `rustc_binary` 或者 `rustc_library` 生成的目标的 `名称` 属性相同的命名。
```suggestion
一个最简清单文件如下所示，并且文件的名称**必须**和上述由 `rustc_binary` 或 `rustc_library` 生成目标的 `name` 属性相同。
```
反引号属性名称应该不能直接翻译，可以在后面打括号。

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +由此，一个上边的 `rustc_binary` 示例清单，清单内容如下：
```suggestion
在上述针对 `rustc_binary` 清单的情况下，相应的内容应为：
```
这样更通顺些？原文 in case of 严重怀疑少个 the。如果觉得赘余的话甚至可以直接写：
```suggestion
在上述 `rustc_binary` 的情况下，相应的清单应为：
```

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +在 `rustc_library` 示例清单中，清单和命名方案是一样的。但是需要留意在 `program.binary` 小节中值的命名上的微小区别。
```suggestion
在 `rustc_library` 的情况下，清单和命名方案是一样的。但是需要留意在 `program.binary` 小节中值的命名上的微小区别。
```
同 Line 201。

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +`_lib_test` 后缀在 `rustc_library` 构建规则中是硬编码，`hello_world_rust` 又一次从构建规则中的 `命名` 属性中得来。
```suggestion
`_lib_test` 后缀在 `rustc_library` 构建规则中是硬编码，`hello_world_rust` 还是从构建规则中的 `name` 属性中得来。
```
同 Line 199。

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +对于 Hello world 例子，测试包需要关联到生成的目标上， `bin_test` （基于目标名称 `bin` 和隐含的 `_test` 后缀），`hello_world_rust_bin_test` （基于 `命名` 小节中的值）。
```suggestion
对于 Hello world 例子，测试包需要关联到生成的目标上， `bin_test` （基于目标名称 `bin` 和隐含的 `_test` 后缀），`hello_world_rust_bin_test` （基于 `name` 小节中的值）。
```
同 Line 199。

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +如果你正在构建的是一个 library ，则 library 的名称会是 `hello_world_rust_lib_test`。
```suggestion
如果你正在构建的是一个库，则库的名称会是 `hello_world_rust_lib_test`。
```

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +注意：为了使用 `fx test`，你不能在你的 `package` 中重载 `package_name="..."` 或 `test_package` 声明。这个问题可以追踪 fxbug.dev/3143
```suggestion
注意：为了使用 `fx test`，你不能在你的 `package` 中重写 `package_name="..."` 或 `test_package` 声明。这个问题可以追踪 fxbug.dev/3143
```
override 重写，overload 重载。（查的）

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +### 有用的  crates
```suggestion
### 有用的 crates
```
多一个空格。

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +* [`matches`]: 提供 `assert_matches!` 宏，使模式断言符合人机工程学。
```suggestion
* [`matches`]: 提供 `assert_matches!` 宏，使模式断言符合工效学。
```
ergonomics 的翻译参见 #91 ，稍后我会 push 该翻译到词汇表。

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +* [`pretty_asssertions`]：提供了一个替代方案 `assert_eq!` 宏，在断言失败时显示不同的颜色。
```suggestion
* [`pretty_asssertions`]：提供了一个可选的 `assert_eq!` 宏，在断言失败时显示彩色的差异。
```
这里上写文没说替代谁，故倾向于判断为“可选”意。用了这个宏之后本来没颜色的差异现在有颜色了。（猜测）

2021-08-26 10:20 UTC, y2-Whyto commented on development/languages/rust/testing.md
> +这些可以包含在你的 `BUILD.gn` 中，在 `test_deps` 下。
```suggestion
这些可以包含在你的 `BUILD.gn` 中的 `test_deps` 下。
```
前者为文件，后者为文件中的依赖区域。

2021-08-27 14:56 UTC, chuyao commented on development/languages/rust/testing.md
> +本文档面向的是在`fuchsia.git`中工作的开发人员，对工作流的描述不太可能适用于IDK消费者。
拍大腿了。这个IDK我也是找了好久，百思不得其解！

2021-08-27 15:37 UTC, chuyao reviewed
太细心了，佩服！感谢指正。

2021-08-27 15:51 UTC, chuyao commented
@y2-Whyto 提交了修改，再次感叹一下小伙伴的细心。

2021-08-28 03:59 UTC, y2-Whyto commented
为何文件改动里显示 `development/languages/rust/ergonomic_inspect.md` 这个文件被删除了？

2021-08-28 14:25 UTC, chuyao commented
> 为何文件改动里显示 `development/languages/rust/ergonomic_inspect.md` 这个文件被删除了？

文件还在我本地仓库里的，之前没翻译完不小心和testing.md一起commit了，撤回了commit。我先把原文件恢复一下。

2021-08-30 14:13 UTC, y2-Whyto approved these changes

2021-08-30 14:14 UTC, merged