translate in common file
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #114
Opened 2021-09-05 09:30 UTC by linenli

2021-09-10 06:59 UTC, chuyao requested changes
提了一些建议，望能修复，加油！

2021-09-10 06:59 UTC, chuyao commented on concepts/drivers/fdf.md
> +Fuchsia驱动框架（FDF）是一整套库，工具，元数据和映像文件的集合，可以帮助驱动开发者进行开发，测试和发布针对Fuchsia的驱动。FDF想要提供一个稳定的ABI去允许驱动开发者仅需开发一次驱动后，就可以应用在Fuchsia内核和平台的多个版本上。
英文专有名词和中文词语之间要留一个空格，参见翻译规范。另下文有多处类似情况，不一一赘述

2021-09-10 06:59 UTC, chuyao commented on concepts/drivers/fdf.md
> +FDF正在不断发展，尚未达到ABI的稳定性。
`achieve ABI stability` 这里的 `stability` 应该译作 `稳定` 而不是 `稳定性`

2021-09-10 06:59 UTC, chuyao commented on concepts/drivers/fdf.md
> +驱动管理器是作为FDF的一部分用于维护和开发二进制文件。它负责在所有平台上加载驱动和管理设备。这是设备加载时要启动的初始程序之一。它在预先配置的路径下寻找到驱动包后，通过运行驱动绑定程序，试图通过一个驱动匹配所有的设备，然后管理设备生命周期。它管理着一个名为设备文件系统（`devfs`）的虚拟文件系统，为来自驱动外部的用户空间服务/组件提供对所有设备的统一访问接口。 `devfs`被挂载在 `/
`Driver manager is a binary maintained and developed as part of FDF.` 应该译作 `驱动管理器是作为 FDF 的一部分而维护和开发的二进制文件` 。即 `驱动管理器` 是个二进制文件，而不是去开发维护其他二进制文件

2021-09-10 06:59 UTC, chuyao commented on concepts/drivers/fdf.md
> +驱动管理器是作为FDF的一部分用于维护和开发二进制文件。它负责在所有平台上加载驱动和管理设备。这是设备加载时要启动的初始程序之一。它在预先配置的路径下寻找到驱动包后，通过运行驱动绑定程序，试图通过一个驱动匹配所有的设备，然后管理设备生命周期。它管理着一个名为设备文件系统（`devfs`）的虚拟文件系统，为来自驱动外部的用户空间服务/组件提供对所有设备的统一访问接口。 `devfs`被挂载在 `/
`This is one of the initial process to be started on device bootup` 译作 `这是将要在设备启动时加载的初始进程之一` 应该要好一些，`process` 是 `进程` ，`bootup` 是 `启动`。

2021-09-10 06:59 UTC, chuyao commented on concepts/drivers/getting_started.md
>      found in the LICENSE file.
copyright 可以原文保留

2021-09-10 06:59 UTC, chuyao commented on concepts/drivers/getting_started.md
> +## 开始指南
有个通俗一点的，叫 `入门指南`

2021-09-10 06:59 UTC, chuyao commented on concepts/drivers/getting_started.md
>  [fdf]: /docs/concepts/drivers/fdf.md
链接中的 /docs 要拿掉，否则提交后链接 404，下同

2021-09-10 06:59 UTC, chuyao commented on concepts/drivers/getting_started.md
>  The sections are listed above in default reading order, but it's perfectly fine to jump around and
这段好像漏了

2021-09-10 06:59 UTC, chuyao commented on concepts/drivers/getting_started.md
> +* [Fuchsia Driver Framework][fdf] - 驱动管理器和驱动主机的概述
Fuchsia Driver Framework 不翻也没问题，但不是专有名词，建议翻译。下同

2021-09-12 07:41 UTC, linenli commented on concepts/drivers/getting_started.md
>      found in the LICENSE file.
copyright未翻译，按照原味注释

2021-09-17 02:22 UTC, chuyao approved these changes

2021-09-17 02:22 UTC, merged