完成concepts/components/v1/component_manifests.md 翻译
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #115
Opened 2021-09-28 09:00 UTC by Submarinee

已完成 concepts/components/v1/component_manifests.md的 翻译

2021-10-13 11:32 UTC, chuyao requested changes
markdown语法有不少问题，可能是输入法问题，望多留意！

2021-10-13 11:32 UTC, chuyao commented on concepts/components/v1/component_manifests.md
> +组件清单 (.cmx) 是文件扩展名为“.cmx”的 JSON 文件。
`` 反引号是markdown语法，无需转成双引号，否则格式就变了

2021-10-13 11:32 UTC, chuyao commented on concepts/components/v1/component_manifests.md
> +可选的 env_vars 属性指定要提供给二进制文件的环境变量，其中数组中的每个元素都使用`"VAR=VALUE"`格式，例如`"RUST_BACKTRACE=1"`。
\`env_vars\` 这里的反引号也要保留

2021-10-13 11:32 UTC, chuyao commented on concepts/components/v1/component_manifests.md
> +## sandbox
建议统一翻译风格，前边几个标题都带了 `属性`，这里也应该加上。`sandbox 属性`

2021-10-13 11:32 UTC, chuyao commented on concepts/components/v1/component_manifests.md
> +到 `dev` 数组。不允许访问单个“misc”设备。
是 \`misc\` 而非 “misc”。另外， individual \`misc\` devices 应该是指 **某些 \`misc\` 类型的设备**，而不是 **单个\`misc\`设备**，注意后边的 `devices` 是复数

2021-10-13 11:32 UTC, chuyao commented on concepts/components/v1/component_manifests.md
> +在 `system` 数组中，那么 `/system/bin` 将出现在从包加载的组件。
-  如果 `bin` 字符串出现在 `system` 数组中** 应该要通顺一些

- `in the namespaces of` 似乎忘了翻译了

2021-10-13 11:32 UTC, chuyao commented on concepts/components/v1/component_manifests.md
> +但它只能访问其[环境](/docs/glossary.md#environment) 中存在的服务。
这里的 `/docs` 要拿掉，否则链接会404

2021-10-13 11:32 UTC, chuyao commented on concepts/components/v1/component_manifests.md
> +这个属性应该由所有新组件定义，很快就会发生迁移以将所有组件转换为定义“服务”。
`services` 在本文中应该属于专有名词，应该按原文保留，况且前面的没翻，这里也就应该不翻。

2021-10-13 11:32 UTC, chuyao commented on concepts/components/v1/component_manifests.md
> +- `config-data`，它将提供任何可用的配置数据。该组件所在的包在 [config-data](/docs/development/components/data.md) 中提供
`/docs` 要拿掉，这个在以后的翻译中要留意

2021-10-13 11:32 UTC, chuyao commented on concepts/components/v1/component_manifests.md
> +- `introspection`, 它请求访问以检查系统。命名空间将位于`/info_experimental`。
`introspect` 应该不是 `检查`，`inspect`才是检查，但我也还没理解这个词的中文含意，字典是 `反省`

2021-10-13 11:32 UTC, chuyao commented on concepts/components/v1/component_manifests.md
> -- `isolated-persistent-storage`, which requests access to persistent storage for
这一段漏了

2021-10-13 11:32 UTC, chuyao commented on concepts/components/v1/component_manifests.md
> +  当前环境中可用的资源。 `deprecated-shell` 功能还暗示了“root-ssl-certificates”和“hub”功能。
注意反引号语法，出现了多次

2021-10-13 11:32 UTC, chuyao commented on concepts/components/v1/component_manifests.md
> +- `durable-data`, 它请求访问设备的读写持久分区，并将其放置在组件命名空间中的“/durable”。
反引号问题

2021-10-13 11:32 UTC, chuyao commented on concepts/components/v1/component_manifests.md
> +参考 [沙盒](/docs/concepts/process/sandboxing.md) 了解有关沙盒的更多信息.
`/docs` 要拿掉

2021-10-13 11:32 UTC, chuyao commented on concepts/components/v1/component_manifests.md
>  [hub]: /docs/concepts/components/v1/hub.md
`/docs` 要拿掉

2021-10-13 11:32 UTC, chuyao commented on concepts/components/v1/component_manifests.md
>  [hub]: /docs/concepts/components/v1/hub.md
后边的 test-components 指向的链接也一样

2021-11-02 12:11 UTC, Submarinee commented
> markdown语法有不少问题，可能是输入法问题，望多留意！

都已经进行修改，麻烦再review下~

2021-11-12 07:27 UTC, chuyao approved these changes

2021-11-12 07:28 UTC, merged