翻译/concepts/usb/request-lifecycle.md
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #121
Opened 2021-11-18 15:52 UTC by luminouser

2022-02-23 09:18 UTC, Mr-Linus requested changes

2022-02-23 09:18 UTC, Mr-Linus commented on concepts/usb/testing.md
> +```
这个地方是不是多了。。。。

2022-06-21 03:35 UTC, bootingman approved these changes

2022-07-07 02:14 UTC, y2-Whyto requested changes

2022-07-07 02:14 UTC, y2-Whyto commented on concepts/usb/testing.md
少 ` ``` `

2022-07-07 02:14 UTC, y2-Whyto commented on concepts/usb/testing.md
> +```
这里没多，好像是下面少个代码块结尾

2022-07-24 10:52 UTC, closed without merging