translate /concepts/graphics/magma/README.md
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #130
Opened 2022-04-03 03:33 UTC by Lyrance

2022-04-25 09:06 UTC, chuyao requested changes
抱歉没有及时 review，提了个修改建议

2022-04-25 09:06 UTC, chuyao commented on concepts/graphics/magma/README.md
> +允许将系统内存页任意映射到GPU地址空间，以便与非连续缓冲区进行DMA。
DMA需要一个允许将系统内存页任意映射到GPU地址空间的内存管理单元，用于进出非连续缓冲区。

2022-04-25 09:06 UTC, huang825172 commented
你好，我是广东外语外贸大学学生会外联部干事黄扬，你的来信我已收到，谢谢你的来信，我将尽快给你答复。

2022-04-25 09:07 UTC, chuyao requested changes
抱歉没有及时 review，提了个修改建议

2022-04-25 13:44 UTC, Lyrance commented
已修改

2022-04-25 13:45 UTC, Lyrance commented
> 你好，我是广东外语外贸大学学生会外联部干事黄扬，你的来信我已收到，谢谢你的来信，我将尽快给你答复。

什么来信？

2022-04-27 09:13 UTC, chuyao approved these changes

2022-04-27 09:13 UTC, merged