/contribute/docs/documentation_standards.md 翻译完成
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #135
Opened 2022-07-11 14:19 UTC by y2-Whyto

该文档在项目开始前翻译完成，特此移除并重新添加，以备校对。

2022-07-20 13:44 UTC, yang-lile requested changes
做了一些修改，需要再次review一下修改的细节。

2022-07-20 13:44 UTC, yang-lile commented on contribute/docs/documentation-standards.md
> +## 文档位置
```suggestion
## 文档定位
```

我觉得译做定位或者目的会好一些。

2022-07-20 13:44 UTC, yang-lile commented on contribute/docs/documentation-standards.md
> +        `/contribute/` 目录包含代码和文档贡献进度以及最佳做法，包含文档准则和风格指南、代码策略以及管理体系。
```suggestion
        `/contribute/` 目录包含代码和文档的贡献进度以及最佳做法，包含文档准则和风格指南、代码策略以及管理体系。
```

加了一个“的”字

2022-07-20 13:44 UTC, yang-lile commented on contribute/docs/documentation-standards.md
> +
```suggestion
## 文档类型

```

补充遗漏

2022-07-20 13:44 UTC, yang-lile commented on contribute/docs/documentation-standards.md
> +        `/reference/` 目录包含生成的关于 Fuchsia 工具和 API 的参考文档，包括 FIDL 和内核的参考文档。
```suggestion
        `/reference/` 目录包含自动生成的关于 Fuchsia 工具和 API 的参考文档，包括 FIDL 和内核的参考文档。
```

由下文可得，文档是自动生成的

2022-07-20 13:44 UTC, yang-lile commented on contribute/docs/documentation-standards.md
> +Fuchsia 的所有文档均使用 Markdown（`.md`）撰写，Fuchsia.dev 使用 [Hoedown Markdown Parser](https://github.com/hoedown/hoedown)。
```suggestion
Fuchsia 的所有文档均使用 Markdown（`.md`）撰写，Fuchsia.dev 使用 [Hoedown Markdown Parser](https://github.com/hoedown/hoedown) 作为 Markdown 文档语法分析器。
```

补充使用的目的，完善语句意义

2022-07-20 13:44 UTC, yang-lile commented on contribute/docs/documentation-standards.md
> +文件和目录名应当为小写，并使用短横线（hyphen）而非下划线（underscore）来分隔单词。在文件或目录名中请仅使用标准 ASCII 字母数字字符。如果文件名包含带有下划线的命令，那么您可以加入下划线。
```suggestion
文件和目录名应当为小写，并使用短横线（hyphen）而非下划线（underscore）来分隔单词。在文件或目录名中请仅使用标准 ASCII 字母数字字符。如果文件名包含带有下划线的命令，那么您可以包含下划线。
```

2022-07-20 13:44 UTC, yang-lile commented on contribute/docs/documentation-standards.md
> +- **使用简单的美国英语撰写。** 使用清晰、直白的美国英语撰写，以使内容易于理解。请使用简单的词汇，保持简洁，并使用（常见）缩写，如 _it's_ 或 _don't_。
```suggestion
- **使用通俗易懂的美国英语撰写。** 使用清晰、直白的美国英语撰写，以使内容易于理解。请使用简单的词汇，保持简洁，并使用（常见）缩写，如 _it's_ 或 _don't_。
```

总领句可以直接包含后面的意思，所以直接译做通俗易懂。

2022-07-21 06:54 UTC, y2-Whyto commented on contribute/docs/documentation-standards.md
> +Fuchsia 的所有文档均使用 Markdown（`.md`）撰写，Fuchsia.dev 使用 [Hoedown Markdown Parser](https://github.com/hoedown/hoedown)。
> 补充使用的目的，完善语句意义

改为了“作为 Markdown 文档语法分析器”，如何？

2022-07-21 06:56 UTC, yang-lile commented on contribute/docs/documentation-standards.md
> +Fuchsia 的所有文档均使用 Markdown（`.md`）撰写，Fuchsia.dev 使用 [Hoedown Markdown Parser](https://github.com/hoedown/hoedown)。
可以的，那就这样改

2022-07-21 07:00 UTC, yang-lile commented on contribute/docs/documentation-standards.md
> +Fuchsia 的所有文档均使用 Markdown（`.md`）撰写，Fuchsia.dev 使用 [Hoedown Markdown Parser](https://github.com/hoedown/hoedown)。
应用这次修改是你来确认是吧，我这边没有找到按钮

2022-07-21 14:29 UTC, y2-Whyto commented on contribute/docs/documentation-standards.md
> +Fuchsia 的所有文档均使用 Markdown（`.md`）撰写，Fuchsia.dev 使用 [Hoedown Markdown Parser](https://github.com/hoedown/hoedown)。
> 应用这次修改是你来确认是吧，我这边没有找到按钮

没问题了approve就行，我来进行合并。

2022-07-23 00:46 UTC, yang-lile approved these changes
已校对无误

2022-07-23 13:40 UTC, merged