翻译 /contribute/governance/rfcs/0002_platform_versioning.md
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #136
Opened 2022-07-13 09:18 UTC by folospace

2022-07-13 10:50 UTC, Lyrance reviewed
辛苦啦

2022-07-13 10:50 UTC, Lyrance commented on contribute/governance/rfcs/0002_platform_versioning.md
> +## 概括
改为“概要”或“摘要”可能更正式一些

2022-07-13 10:50 UTC, Lyrance commented on contribute/governance/rfcs/0002_platform_versioning.md
> +*向后兼容性* 是指较新版本的 Fuchsia 能够运行旨在在旧版本 Fuchsia 上运行的二进制文件。
“旨在”或许有些拗口，可以换为：
能够运行原本用于在旧版本 Fuchsia 上运行的二进制文件。

2022-07-13 10:50 UTC, Lyrance commented on contribute/governance/rfcs/0002_platform_versioning.md
> +IDK 工具定义了 Fuchsia IDK 工具和开发环境集成器的环境之间的合约。
contract可以翻译为“协定”或“协议”，上面的同理

2022-07-13 10:50 UTC, Lyrance commented on contribute/governance/rfcs/0002_platform_versioning.md
> +具体来说，如果应用程序在给定的 Fuchsia 版本上运行，那么应用程序应继续在 Fuchsia 的未来版本上工作，
如果（一个）应用程序在给定的 Fuchsia 版本上运行

2022-07-13 10:50 UTC, Lyrance commented on contribute/governance/rfcs/0002_platform_versioning.md
> +除非 Fuchsia 故意放弃对应用程序的支持。
除非 Fuchsia 故意放弃对（该）应用程序的支持。

2022-07-13 10:50 UTC, Lyrance commented on contribute/governance/rfcs/0002_platform_versioning.md
> +与其保持旧 ABI 版本暗指的完整语义，
（相比于）保持旧 ABI 版本暗指的完整语义，

2022-07-13 10:50 UTC, Lyrance commented on contribute/governance/rfcs/0002_platform_versioning.md
> +虽然不是立即需要，组件最终将希望根据 ABI 版本来调整能力路线。
capability routes是“路由功能”？“路由能力”？

2022-07-13 10:50 UTC, Lyrance commented on contribute/governance/rfcs/0002_platform_versioning.md
> +类似地，平台可能希望将特定遗留组件的功能路由到提供兼容性填充程序的专用目的地。
目的地换为目标，可以适当调整一下语序，定语有点太多了

2022-07-13 10:50 UTC, Lyrance commented on contribute/governance/rfcs/0002_platform_versioning.md
> +例如，我们可以定义一个路由 *quirk*，它适用于在 quirk 表中具有该 quirk 的特定遗留组件。
gets applied for没翻译出来？

2022-07-13 10:50 UTC, Lyrance commented on contribute/governance/rfcs/0002_platform_versioning.md
> +项目将需要以相同的安全努力来处理支持旧 ABI 版本的代码。
项目将需要在安全方面付出相同的努力来处理支持旧 ABI 版本的代码。

2022-07-13 10:50 UTC, Lyrance commented on contribute/governance/rfcs/0002_platform_versioning.md
> +应该更新平台的文档以注释每个 API 及其在生命周期中的当前阶段及其生命周期历史（例如，何时引入、弃用和/或删除 API）。
及其在生命周期中的当前阶段和生命周期历史

2022-07-13 10:50 UTC, Lyrance commented on contribute/governance/rfcs/0002_platform_versioning.md
> +例如，每个文件系统都有自己的版本标识符，用于文件系统的磁盘表示和内存代码之间的约定。
“协定”“协议”，下面同理

2022-07-18 01:53 UTC, folospace commented on contribute/governance/rfcs/0002_platform_versioning.md
> +虽然不是立即需要，组件最终将希望根据 ABI 版本来调整能力路线。
路由功能比较符合语义，已修正

2022-07-19 10:49 UTC, y2-Whyto commented on contribute/governance/rfcs/0002_platform_versioning.md
> +## 为什么现在？
请将本句扩充完整。

2022-07-19 10:50 UTC, y2-Whyto commented
@Lyrance 本篇校对完了吗？如果校对完了记得 approve，之后我会进行合并。

2022-07-19 11:18 UTC, Lyrance commented
> @Lyrance 本篇校对完了吗？如果校对完了记得 approve，之后我会进行合并。

ok

2022-07-22 01:38 UTC, folospace commented on contribute/governance/rfcs/0002_platform_versioning.md
> +## 为什么现在？
@Lyrance 怎么扩充？

"为什么现在进行版本控制？"   

我不确定

2022-07-22 03:07 UTC, Lyrance commented on contribute/governance/rfcs/0002_platform_versioning.md
> +## 为什么现在？
可以的

2022-07-23 01:28 UTC, Lyrance requested changes
请参照general-translation-guide.md来修改格式，比如不要使用斜体

2022-07-25 02:09 UTC, folospace commented
> 请参照general-translation-guide.md来修改格式，比如不要使用斜体

已经去掉斜体

2022-07-26 03:28 UTC, y2-Whyto commented
> > 请参照general-translation-guide.md来修改格式，比如不要使用斜体
> 
> 已经去掉斜体

烦请您认真阅读一下[文档总体翻译指南](https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN/blob/2022/general-translation-guide.md)，斜体格式需要进行替换，而不是简单地移除。

2022-07-26 09:09 UTC, folospace commented
抱歉，翻译细节过于复杂，我没时间深入理解，所以我放弃了

2022-07-26 09:09 UTC, closed without merging