翻译contribute/governance/rfcs/0007_remove_thread_killing.md
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #153
Opened 2022-07-21 09:52 UTC by Cwolf9

2022-07-23 01:19 UTC, Lyrance requested changes

2022-07-23 01:19 UTC, Lyrance commented on contribute/governance/rfcs/0007_remove_thread_killing.md
> +## Summary
请翻译标题，下面同理

2022-07-23 01:19 UTC, Lyrance commented on contribute/governance/rfcs/0007_remove_thread_killing.md
> +在 Fuchsia 上，和其他系统一样，杀死一个线程是异步完成的； 对于正在运行的线程，没有实用的方法来确定可以安全终止线程的确切位置。 对于阻塞（等待）状态的线程，通常更安全且简单的解决方案是添加逻辑，以便在唤醒后线程自行退出。(todo)
todo是啥

2022-07-23 07:05 UTC, Cwolf9 commented on contribute/governance/rfcs/0007_remove_thread_killing.md
> +## Summary
已修改标题等格式问题。

2022-07-23 07:05 UTC, Cwolf9 commented on contribute/governance/rfcs/0007_remove_thread_killing.md
> +在 Fuchsia 上，和其他系统一样，杀死一个线程是异步完成的； 对于正在运行的线程，没有实用的方法来确定可以安全终止线程的确切位置。 对于阻塞（等待）状态的线程，通常更安全且简单的解决方案是添加逻辑，以便在唤醒后线程自行退出。(todo)
还没翻译完成时写的，已删除。

2022-07-23 07:17 UTC, Lyrance approved these changes, later dismissed

2022-07-24 01:51 UTC, y2-Whyto reviewed
几个小修。另外希望以后注意将注释标记和原文放在不同的段落里，以便GitHub给出更简明的差异界面。

2022-07-24 01:51 UTC, y2-Whyto commented on contribute/governance/rfcs/0007_remove_thread_killing.md
> +用户态没有合理的用途来杀死单个线程。暴露此类能力会为不良做法提供支持。
```suggestion
对于用户态而言，杀死单个线程的做法没有合理用途。暴露此类能力会为不良做法提供支持。
```

这样改语句会更通顺些？

2022-07-24 01:51 UTC, y2-Whyto commented on contribute/governance/rfcs/0007_remove_thread_killing.md
> +在 Fuchsia 上，和其他系统一样，杀死一个线程是异步完成的；对于正在运行的线程，没有实用的方法来确定可以安全终止线程的确切位置。对于阻塞（等待）状态的线程，通常更安全且简单的解决方案是添加逻辑，以便在唤醒后线程自行退出。
```suggestion
在 Fuchsia 上，和其他系统一样，杀死一个线程是异步完成的；对于正在运行的线程，没有实用的方法来确定可安全终止线程的确切位置。对于阻塞（等待）状态的线程，通常更安全且简单的解决方案是添加逻辑，以便在唤醒后线程自行退出。
```
“可安全终止进程”（形成一个紧密的名词）或“可以安全终止的进程”（明确的定语成分）。这两种表述都更好一些。原始译法里这个位置写得不太好区分。

2022-07-24 01:51 UTC, y2-Whyto commented on contribute/governance/rfcs/0007_remove_thread_killing.md
> +* 内存可能会泄漏。至少线程堆栈可能泄露，但通常还有许多其他部分的内存会泄露。
```suggestion
* 内存可能会泄漏。至少线程堆栈可能泄漏，但通常还有许多其他部分的内存会泄漏。
```
“泄漏”？“泄露”？

2022-07-24 01:51 UTC, y2-Whyto commented on contribute/governance/rfcs/0007_remove_thread_killing.md
> +* 以系统调用的方式杀死一个线程会使进程处于未知状态。内核没有影响，但该进程无法知道发生了什么以及没有发生什么。
```suggestion
* 以系统调用的方式杀死一个线程会使进程处于未知状态。这对内核没有影响，但该进程无法知道发生了什么以及没有发生什么。
```

请确保语句通顺完整。

2022-07-24 01:51 UTC, y2-Whyto commented on contribute/governance/rfcs/0007_remove_thread_killing.md
> +将遵循完整的 Fuchsia Large Scale Change (LSC) 流程，以确保这一变化被正确测试。
```suggestion
将遵循完整的 Fuchsia 大型变更（Large Scale Change，LSC）流程，以确保这一变化被正确测试。
```

这里应该翻译，并标注。

2022-07-24 03:51 UTC, Cwolf9 commented on contribute/governance/rfcs/0007_remove_thread_killing.md
> +将遵循完整的 Fuchsia Large Scale Change (LSC) 流程，以确保这一变化被正确测试。
好的，谢谢，几个小修和注释标记格式已经更正。

2022-07-24 04:10 UTC, y2-Whyto approved these changes
下次记得将解决了的 comment 点一下“resolve conversation”，方便了解接受了那些更改。

2022-07-24 04:10 UTC, merged