translate build_fuchsia.md
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #155
Opened 2022-07-21 14:35 UTC by user-wy

2022-07-23 01:41 UTC, Lyrance requested changes

2022-07-23 01:41 UTC, Lyrance commented on get-started/build_fuchsia.md
> +这篇文档将引导你在主机上如何配置并编译 Fuchsia。
主语统称为您，参照general-translation-guide.md

2022-07-23 01:41 UTC, Lyrance commented on get-started/build_fuchsia.md
> +- x86-64 Linux (只支持 Debian 系列的)
请避免口头语的使用，比如此句去掉“的”

2022-07-23 01:41 UTC, Lyrance commented on get-started/build_fuchsia.md
> +编译调优的话，需要下面的服务：
避免口头语的使用，其他地方同理

2022-07-23 01:41 UTC, Lyrance commented on get-started/build_fuchsia.md
> +如果不能访问 Goma，但是想加速本地编译时间，那就使用 <code>[ccache](https://ccache.dev/){:.external}</code> 来缓存来进行增量编译。
那就使用改为可以使用，文档需要书面化语言

2022-07-23 01:41 UTC, Lyrance commented on get-started/build_fuchsia.md
> +  至于 macOS ，参考 [在 Mac 上使用 CCache](https://chromium.googlesource.com/chromium/src.git/+/HEAD/docs/ccache_mac.md){:.external} 中的安装步骤。
对于macOS

2022-07-23 01:41 UTC, Lyrance commented on get-started/build_fuchsia.md
> +注意：编译时间一般为 90 分钟。
最多需要90分钟

2022-07-23 01:41 UTC, Lyrance commented on get-started/build_fuchsia.md
>  <!-- Reference links -->
咋没了？

2022-07-23 01:42 UTC, Lyrance commented
请注意书面语的使用，有些小地方我没标出来也请改一下

2022-07-24 02:10 UTC, y2-Whyto reviewed
请自行检查一下问题，再做提交：
1. “您”。
2. 祈使句尽量添加“请”。
3. 过于口语化的语言风格。
4. 正文中的标点符号（逗号、句号、括号）是否为全角。
5. 多余的空格。
前三条请尽可能修改好。后两条如果不方便则可以在校对时修改。

2022-07-24 02:10 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +- x86-64 Linux (只支持 Debian 系列的)
```suggestion
- x86-64 Linux（只支持基于 Debian 的发行版）
```
还请注意标点符号使用。

2022-07-24 02:10 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +注意：编译时间一般为 90 分钟。
用“可能需要长达”更好一些？

2022-07-24 02:10 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +如果不能访问 Goma，但是想加速本地编译时间，那就使用 <code>[ccache](https://ccache.dev/){:.external}</code> 来缓存来进行增量编译。
则可以使用

2022-07-24 02:10 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +当你修改源代码后，要运行命令 `fx build` 来增量编译，或则运行 `fx -i build` 命令来开启一个监视进程，这个监视进程一旦发现源码有更新就会自动编译。
```suggestion
当你修改源代码后，要运行命令 `fx build` 来增量编译，或者运行 `fx -i build` 命令来开启一个监视进程，这个监视进程一旦发现源码有更新就会自动编译。
```
错别字。

2022-07-24 02:10 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +想要更多编译 Fuchsia 的相信信息，参考 [开始编译](/development/build/fx.md#execute-a-build)。
```suggestion
要获取关于编译 Fuchsia 的更多信息，请参阅[开始编译](/development/build/fx.md#execute-a-build)。
```
1. 固定句式。
2. 错别字。
3. 多余空格。

2022-07-24 02:10 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +如果你能访问 Goma， 使用下面的命令来开启 Goma 客户端：
```suggestion
如果您能访问 Goma，那么请使用下面的命令来开启 Goma 客户端：
```

2022-07-24 02:37 UTC, user-wy commented on get-started/build_fuchsia.md
> +注意：编译时间一般为 90 分钟。
up 表示最多， 这样翻译是忠于原文了。 但是一般说的话，都是用大致，或者说大概。所以如果忠于原文的话，可以再组织下语言。感觉有点不通顺。

2022-07-24 02:37 UTC, user-wy commented on get-started/build_fuchsia.md
>  <!-- Reference links -->
下面的参考链接应该是在文中的超链接。所以就没有翻译。

2022-07-24 02:43 UTC, user-wy commented
已修改

2022-07-24 07:18 UTC, Lyrance commented on get-started/build_fuchsia.md
>  <!-- Reference links -->
链接的标题需要翻译吗？ @y2-Whyto

2022-07-26 06:34 UTC, ctzsm commented on get-started/build_fuchsia.md
> +# 配置和编译 Fuchsia {#configure-and-build-fuchsia}
build应该翻译为构建，编译只是构建的一种步骤。

2022-07-26 12:25 UTC, user-wy commented
review is done.

2022-07-28 13:47 UTC, y2-Whyto reviewed
进行了一些详细校对。请合理使用机器翻译，尽最大可能不要意译。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +这篇文档将引导您在主机上如何配置并编译 Fuchsia。
```suggestion
这篇文档将引导您在主机上配置并构建 Fuchsia。
```

“如何”有些杂糅。

“build”翻译为“构建”，参见 https://developer.android.com/studio/run?hl=zh-cn 。稍后我会添加到翻译术语表。**请您对后文中的“编译”进行检查，并批量替换。**

“编译”一般会写“compile”。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +1. [编译调优（可选）](#speed-up-the-build)
```suggestion
1. [提升构建速度（可选）](#speed-up-the-build)
```

参考 https://developer.android.com/ndk/guides/prebuilts 和 https://developer.android.com/training/improving-layouts/loading-ondemand 。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +## 1. 准备 {#prerequisites}
```suggestion
## 1. 前提条件 {#prerequisites}
```

https://support.google.com/analytics/answer/11548051?hl=zh-Hans

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +* [准备源码](#source-code-setup)
```suggestion
* [源代码设置](#source-code-setup)
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +### 准备源码 {#source-code-setup}
```suggestion
### 源代码设置 {#source-code-setup}
```
源**代**码，请不要随意缩写，并进行对该表达方式进行批量查找替换。为此我已将其添加至翻译术语表。也恳请翻译时及时查阅 Google 公司支持文档。

https://developer.android.com/studio/projects/add-native-code

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +Fuchsia 的编译支持如下架构的机器：
```suggestion
您只能在下列主机架构之一的机器上构建 Fuchsia：
```

此处存在明显意译，并且缺失了信息，如“only”。请尽量不要意译，对语意表达有影响，而且会给校对带来麻烦。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +注意：Windows 和 ARM64 是不支持的。
```suggestion
注意：不支持 Windows 和 ARM64。
```
调整语序。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +## 2. 配置设置项 {#set-your-build-configuration}
```suggestion
## 2. 设置构建配置 {#set-your-build-configuration}
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +Fuchsia 的编译设置项告诉编译系统如何编译，以及编译什么架构的文件。
```suggestion
Fuchsia 的构建配置告诉构建系统需要构建的产品和构建所面向的架构。
```

意译了， 而且内容有偏差。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +设置您的 Fuchsia 编译选项，可以运行 [`fx set`][fx-set-reference] 命令：
```suggestion
要设置您的 Fuchsia 构建配置，请运行以下 [`fx set`][fx-set-reference] 命令：
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +替换以下选项：
```suggestion
请替换以下选项：
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +* `PRODUCT`: 编译的目标文件类型, 比如可以设置为： `core` 和 `workstation_eng`.
```suggestion
* `PRODUCT`（产品）：编译的目标文件类型, 比如可以设置为： `core` 和 `workstation_eng`.
```

可以参阅去年的相关翻译文档 https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN/blob/2021/concepts/build_system/boards_and_products.md。

另外请注意标点符号。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +* `BOARD`: 编译的可执行文件架构，比如：`x64` 和 `qemu-x64`
```suggestion
* `BOARD`（板型）：编译的可执行文件架构，比如：`x64` 和 `qemu-x64`
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +下面的示例设置了编译选项为 `core.qemu-x64`:
```suggestion
下面的示例将一项构建配置设置为 `core.qemu-x64`：
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +  * `core` 就是选择了特性最小化的 Fuchsia， 当然包括了常见的网络相关。
```suggestion
  * `core` 是 Fuchsia 具备最小功能集的产品，包括常用的网络功能。
```

请把表达方式再打磨一下。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +  * `qemu-x64` 这个选项设置了编译架构为在开源的虚拟机 （FEMU）中的 x64 架构 [QEMU][qemu]{:.external}.
```suggestion
  * `qemu-x64` 是指 Fuchsia 模拟器（Fuchsia emulator，FEMU）的 x64 架构这一板型。FEMU 基于开源模拟器 [QEMU][qemu]{:.external}。
```

原译文表达有所缺失，也不够通顺。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +在看另一个编译选项示例，下面这个命令配置了 [在设备中安装 Fuchsia 工作站][build-workstation] 中常用的一个架构, `workstation_eng.x64`:
```suggestion
另外，下面的示例将构建配置设置为 `workstation_eng.x64`，这常用于[在设备上安装 Fuchsia 工作站产品][build-workstation]：
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +* `PRODUCT`: 构建的目标文件类型, 比如可以设置为： `core` 和 `workstation_eng`.
```suggestion
* `PRODUCT`（产品）：您想要构建的 Fuchsia 产品，比如：`core` 和 `workstation_eng`。
```

根据 issue 讨论的结果进行了标注。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +* `BOARD`: 构建的可执行文件架构，比如：`x64` 和 `qemu-x64`
```suggestion
* `BOARD`（板型）：产品的架构，比如：`x64` 和 `qemu-x64`。
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +下面的示例设置了构建选项为 `core.qemu-x64`:
```suggestion
下面的示例将一项构建配置设置为 `core.qemu-x64`：
```

请注意标点符号。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +  * `qemu-x64` 这个选项设置了构建架构为在开源的虚拟机 （FEMU）中的 x64 架构 [QEMU][qemu]{:.external}.
```suggestion
  * `qemu-x64` 是 Fuchsia 模拟器（FEMU）的 x64 架构这一板型，FEMU 基于开源模拟器 [QEMU][qemu]{:.external}。
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +在看另一个构建选项示例，下面这个命令配置了 [在设备中安装 Fuchsia 工作站][build-workstation] 中常用的一个架构, `workstation_eng.x64`:
```suggestion
另外，下面的例子将一项编译配置设置为 `workstation_eng.x64`，这常用于[在设备上安装 Fuchsia 工作站][build-workstation]：
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +如果想查看更详细的构建选项介绍，参考 [配置构建选项](/development/build/fx.md#configure-a-build)
```suggestion
要获取关于构建配置的更多信息，请参阅[配置构建](/development/build/fx.md#configure-a-build)。
```

固定句式，漏标点。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +1. [构建调优（可选）](#speed-up-the-build)
```suggestion
1. [提升构建速度（可选）](#speed-up-the-build)
```

可以参考有关 Android 支持文档的翻译方式。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +1. [准备](#prerequisites)
```suggestion
1. [前提条件](#prerequisites)
```

Google 公司文档中常用。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +这篇文档将引导您在主机上如何配置并构建 Fuchsia。
```suggestion
这篇文档将引导您在主机上配置并构建 Fuchsia。
```

“如何”杂糅。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +根据文档 [下载 Fuchsia 源码](/get-started/get_fuchsia_source.md) 指示下载 Fuchsia 的源码，然后在您的机器上设置开发环境。
```suggestion
根据文档[下载 Fuchsia 源代码](/get-started/get_fuchsia_source.md)指示下载 Fuchsia 的源代码，然后在您的计算机上设置开发环境。
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +Fuchsia 的构建支持如下架构的机器：
```suggestion
您只能在具有下列主机架构之一的计算机上构建 Fuchsia：
```

漏译严重（如“only”）。请参考谷歌翻译。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +Fuchsia 的构建设置项告诉构建系统如何构建，以及构建什么架构的文件。
```suggestion
Fuchsia 的构建配置告诉构建系统进行构建的产品，以及构建面向的平台。
```

“如何构建”原文没有。请不要根据自己的理解转述。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +设置您的 Fuchsia 构建选项，可以运行 [`fx set`][fx-set-reference] 命令：
```suggestion
要设置您的 Fuchsia 构建配置，请运行 [`fx set`][fx-set-reference] 命令：
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +## 3. 构建调优（可选） {#speed-up-the-build}
```suggestion
## 3. 提升构建速度（可选） {#speed-up-the-build}
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +注意：这一步不是必选项，但是建议您设置，因为设置了这一步能节省很多的构建时间。
```suggestion
注意：这一步对于构建 Fuchsia 而言并不是必需的，但是可以在您构建 Fuchsia 时节省很多时间，因此建议您完成该步骤。
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +构建调优的话，需要下面的服务：
```suggestion
要提升 Fuchsia 构建速度，您可以使用下列服务之一：
```
“的话”不是正式用语。“需要”从何而来？

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +*   [使用 Goma](#enable-goma)
```suggestion
*   [启用 Goma](#enable-goma)
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +### 使用 Goma {#enable-goma}
```suggestion
### 启用 Goma {#enable-goma}
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +[Goma](https://chromium.googlesource.com/infra/goma/server/){:.external} 是一个分布式构建服务，常用在一些开源项目中，如 Chrome，Android 以及 Fuchsia。
```suggestion
[Goma](https://chromium.googlesource.com/infra/goma/server/){:.external} 是一个分布式编译器服务，适用于 Chrome、Android 和 Fuchsia 等开源项目。
```

参考谷歌翻译。

“compiler”编译器。

中文标点。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +如果您能访问 Goma， 那么请使用下面的命令来开启 Goma 客户端：
```suggestion
如果您能访问 Goma， 请在您的计算机上 Goma 客户端：
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +如果不能访问 Goma，但是想加速本地构建时间，则可以使用 <code>[ccache](https://ccache.dev/){:.external}</code> 来缓存来进行增量构建。
```suggestion
如果您无法访问 Goma，但想在本地加速构建，则可以使用 <code>[ccache](https://ccache.dev/){:.external}</code> 缓存之前构建的产物。
```

“加速”“时间”？有语病。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +  在 Linux 中使用 `ccache`，安装如下安装包：
```suggestion
  要在 Linux 上使用 `ccache`，请安装如下安装包：
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +  对于 macOS ，参考 [在 Mac 上使用 CCache](https://chromium.googlesource.com/chromium/src.git/+/HEAD/docs/ccache_mac.md){:.external} 中的安装步骤。
```suggestion
  对于 macOS ，请参阅[在 Mac 上使用 CCache](https://chromium.googlesource.com/chromium/src.git/+/HEAD/docs/ccache_mac.md){:.external} 中的安装步骤。
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +如果您的 `CCACHE_DIR` 环境变量指向一个存在的路径，`ccache` 就会自动开启。
```suggestion
如果您的 `CCACHE_DIR` 环境变量指向已有路径，那么 `ccache` 就会自动开启。
```
补全连词。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +如果想关闭这个特性，可以指定下面的标志为 `fx set`：
```suggestion
要覆盖此默认行为，请为 `fx set` 指定以下标志：
```

参考谷歌翻译。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +*   强制使用 `ccache`，即使其他的加速项可以使用：
```suggestion
*   即使其他的加速项可用，也要强制使用 `ccache`，则：
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +*   关闭 `ccache`：
```suggestion
*   要禁用 `ccache`：
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +使用如下命令构建 Fuchsia：
```suggestion
要构建 Fuchsia，请运行以下命令：
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +当您修改源代码后，要运行命令 `fx build` 来增量构建，或者运行 `fx -i build` 命令来开启一个监视进程，这个监视进程一旦发现源码有更新就会自动构建。
```suggestion
当您修改源代码后，请再次运行命令 `fx build` 进行增量构建，或者运行 `fx -i build` 命令来开启一个监视进程，这个监视进程会在发现源代码更新时自动构建。
```

这样调整可能会好些，原译文有点生硬。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +要获取关于构建 Fuchsia 的更多信息，请参考参阅[开始构建](/development/build/fx.md#execute-a-build)。
```suggestion
要获取关于构建 Fuchsia 的更多信息，请参阅[执行构建](/development/build/fx.md#execute-a-build)。
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +## 下一步
```suggestion
## 后续步骤
```

参见 https://support.google.com/google-ads/answer/7653505?hl=zh-Hans 。请顺便一并添加至翻译术语表。

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +关于如何在您的主机上打开 Fuchsia 模拟器 （FEMU），参考 [开启 Fuchsia 模拟器](/get-started/set_up_femu.md)。
```suggestion
要在您的计算机上启动 Fuchsia 模拟器 （FEMU），请参阅[开启 Fuchsia 模拟器](/get-started/set_up_femu.md)。
```

2022-07-28 13:47 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +如果您无论如何都想要在硬件平台上运行 Fuchsia， 可以参考 [在硬件设备中安装 Fuchsia](/development/hardware/README.md)。
```suggestion
不过，如果您想在硬件设备上运行 Fuchsia，请参阅[在设备上安装 Fuchsia](/development/hardware/README.md)。
```

“However”，不过。

2022-07-28 13:49 UTC, y2-Whyto commented on get-started/build_fuchsia.md
>  <!-- Reference links -->
> 链接的标题需要翻译吗？ @y2-Whyto

那些是超链接的引用，在前文超链接的位置做锚点用的。不是正文。不可以翻译。

2022-07-30 04:42 UTC, y2-Whyto reviewed
之前遗漏了这几个地方。

2022-07-30 04:42 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +另外，下面的例子将一项编译配置设置为 `workstation_eng.x64`，这常用于[在设备上安装 Fuchsia 工作站][build-workstation]：
```suggestion
另外，下面的例子将一项构建配置设置为 `workstation_eng.x64`，这常用于[在设备上安装 Fuchsia 工作站][build-workstation]：
```

2022-07-30 04:42 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +* `BOARD`（板型）：编译的可执行文件架构，比如：`x64` 和 `qemu-x64`。
```suggestion
* `BOARD`（板型）：产品的可执行文件架构，比如：`x64` 和 `qemu-x64`。
```

2022-07-30 04:42 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +1. [配置设置项](#set-your-build-configuration)
```suggestion
1. [设置构建配置](#set-your-build-configuration)
```

2022-07-30 04:42 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +1. [构建](#build-fuchsia)
```suggestion
1. [构建 Fuchsia](#build-fuchsia)
```

2022-07-30 04:42 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +## 4. 构建 {#build-fuchsia}
```suggestion
## 4. 构建 Fuchsia {#build-fuchsia}
```

2022-07-30 04:42 UTC, y2-Whyto commented on get-started/build_fuchsia.md
> +## 1. 准备 {#prerequisites}
> ```suggestion
> ## 1. 前提条件 {#prerequisites}
> ```
> 
> https://support.google.com/analytics/answer/11548051?hl=zh-Hans

这里没有修改。

2022-07-31 14:22 UTC, user-wy commented
review done.

2022-08-01 12:43 UTC, y2-Whyto approved these changes

2022-08-03 13:37 UTC, Lyrance approved these changes

2022-08-05 08:48 UTC, merged