翻译 get-started/_common/fidl/_fidl_intro.md
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #168
Opened 2022-07-26 20:09 UTC by Cwolf9

2022-07-27 02:05 UTC, Lyrance requested changes

2022-07-27 02:05 UTC, Lyrance commented on get-started/_common/fidl/_fidl_intro.md
> +Fuchsia 接口定义语言（FIDL）是用来描述 Fuchsia 程序使用的进程间通信（IPC）协议的语言。FIDL 提供了一种简化的声明语法，供供应商将接口定义为一种**协议**。支持的数据类型包括整数、浮点数、布尔运算、字符串和[句柄][glossary.handle]。这些可以被组织成更复杂的数组、向量、结构体、表格和联合体。
尽量避免叠字，供供应商可以换一种说法

2022-07-27 02:05 UTC, Lyrance commented on get-started/_common/fidl/_fidl_intro.md
> +FIDL支持以下方法类型：
FIDL 支持以下方法类型：
空格问题

2022-07-27 02:05 UTC, Lyrance commented on get-started/_common/fidl/_fidl_intro.md
> +* **事件**：必要时，服务器端可以向客户端发送非请求信息，称之为事件。事件在 `->` 操作符的返回端声明其方法名称。在 `Echo` 的例子中，`OnString()` 方法是一个事件。
“称之为事件”缺少主语

2022-07-29 10:48 UTC, Lyrance approved these changes

2022-07-30 04:33 UTC, y2-Whyto approved these changes

2022-07-30 04:33 UTC, merged