翻译 get-started/_common/components/_organizing_intro.md
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #173
Opened 2022-07-31 17:42 UTC by tabidachinokaze

翻译 get-started/_common/components/_organizing_intro.md

2022-08-01 02:25 UTC, Lyrance requested changes

2022-08-01 02:25 UTC, Lyrance commented on get-started/_common/components/_organizing_intro.md
> +任何父组件及其所有子组件在树中形成一个称为**领域**的组。领域使父级能够控制哪些功能流入和流出其组件的子树，从而创建功能边界。这种封装允许领域在内部进行重组，而不会影响依赖于其公开功能的外部组件。
那些

2022-08-01 02:25 UTC, Lyrance commented on get-started/_common/components/_organizing_intro.md
> +![图表展示了组件实例被组织成一个树，父组件通过“功能路由”确定每个子组件可用的功能。](/get-started/images/components/component-topology.png){: width="616"}
Capability routing 请参照以往的翻译

2022-08-01 02:25 UTC, Lyrance commented on get-started/_common/components/_organizing_intro.md
> +在上图中，`fuchsia.example.Foo` 协议功能通过组件实例树从提供者路由到客户端。组件使用 `use` 关键字声明它们**需要**的功能：
Capability 翻译为能力 下同

2022-08-01 15:26 UTC, tabidachinokaze commented on get-started/_common/components/_organizing_intro.md
> +![图表展示了组件实例被组织成一个树，父组件通过“功能路由”确定每个子组件可用的功能。](/get-started/images/components/component-topology.png){: width="616"}
[以往的翻译](https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN/blob/308ef029e26f31ba1adcb30f02295e9d939f518c/concepts/diagnostics/logs/attribution.md?plain=1#L124)是**功能路由**

2022-08-01 15:33 UTC, tabidachinokaze commented on get-started/_common/components/_organizing_intro.md
> +在上图中，`fuchsia.example.Foo` 协议功能通过组件实例树从提供者路由到客户端。组件使用 `use` 关键字声明它们**需要**的功能：
上面也出现过capability，是否都改为能力？

2022-08-02 01:00 UTC, Lyrance commented on get-started/_common/components/_organizing_intro.md
> +![图表展示了组件实例被组织成一个树，父组件通过“功能路由”确定每个子组件可用的功能。](/get-started/images/components/component-topology.png){: width="616"}
我记得群里不是说过capability要翻译成功能吗？还没有统一结果吗

2022-08-05 08:57 UTC, y2-Whyto commented on get-started/_common/components/_organizing_intro.md
> +任何父组件及其所有子组件在树中形成一个称为**领域**的组。领域使父级能够控制哪些功能流入和流出其组件的子树，从而创建功能边界。这种封装允许领域在内部进行重组，而不会影响依赖于其公开功能的外部组件。
```suggestion
任何父组件及其所有子组件在树中形成一个称为**领域**的组。领域使父级能够控制那些功能流入和流出其组件的子树，从而创建功能边界。这种封装允许领域在内部进行重组，而不会影响依赖于其公开功能的外部组件。
```

@tabidachinokaze

2022-08-08 04:32 UTC, y2-Whyto commented
@tabidachinokaze issue 投票方案已经出来了，麻烦把译文中的 capability / capabilities 对应词替换为“能力”吧，之后要求 @Lyrance re-review 一下

2022-08-09 15:23 UTC, Lyrance requested changes

2022-08-09 15:23 UTC, Lyrance commented on get-started/_common/components/_organizing_intro.md
> +注意：要获取关于组件组织的更多详细信息，请参阅[组件拓扑](/concepts/components/v2/topology.md).
最后改为句号

2022-08-10 02:23 UTC, Lyrance approved these changes

2022-08-10 12:42 UTC, y2-Whyto approved these changes

2022-08-10 12:42 UTC, merged