重新提交驱动框架简介
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #184
Opened 2022-08-07 00:49 UTC by wwvm

合并了原先提交的PR中的审核意见

2022-08-08 09:03 UTC, y2-Whyto approved these changes

2022-08-08 09:04 UTC, y2-Whyto commented
@Lyrance

2022-08-09 15:26 UTC, Lyrance requested changes

2022-08-09 15:26 UTC, Lyrance commented on get-started/_common/components/_product_driver.md
> +注：要获取关于驱动框架的更多细节，请参阅[Fuchsia 驱动框架](/development/drivers/concepts/fdf.md).
最后一个标点符号请改为中文句号

2022-08-10 04:02 UTC, merged