组件简介
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #185
Opened 2022-08-07 02:24 UTC by wwvm

翻译 get-started/_common/components/_product_intro.md

2022-08-08 09:09 UTC, y2-Whyto reviewed
小建议

2022-08-08 09:09 UTC, y2-Whyto commented on get-started/_common/components/_product_intro.md
> +组件构成了在 Fuchsia 用户空间中运行的软件的基础。 到目前为止，您所探索的组件是运行 Fuchsia 的所有产品通用的核心平台的一部分。Fuchsia 产品由平台组件和特定产品元素组成，以满足设备硬件和用户体验的独特需求。 在本节中，您将探索 Fuchsia 如何构建组件以实现产品级定制。
```suggestion
组件构成了在 Fuchsia 用户空间中运行的软件的基础。 到目前为止，您所探索的组件是运行 Fuchsia 的所有产品通用的核心平台的一部分。Fuchsia 产品由平台组件和特定于产品的元素组成，以满足设备硬件和用户体验的独特需求。 在本节中，您将探索 Fuchsia 如何构建组件以实现产品级定制。
```

2022-08-08 09:10 UTC, y2-Whyto commented
@Lyrance

2022-08-09 11:28 UTC, y2-Whyto submitted a review, later dismissed
小建议

2022-08-09 15:34 UTC, Lyrance requested changes

2022-08-09 15:34 UTC, Lyrance commented on get-started/_common/components/_product_intro.md
> +组件构成了在 Fuchsia 用户空间中运行的软件的基础。 到目前为止，您所探索的组件是运行 Fuchsia 的所有产品通用的核心平台的一部分。Fuchsia 产品由平台组件和特定于产品的元素组成，以满足设备硬件和用户体验的独特需求。 在本节中，您将探索 Fuchsia 如何构建组件以实现产品级定制。
“在本节中”前面多了空格

2022-08-09 15:34 UTC, Lyrance commented on get-started/_common/components/_product_intro.md
> +![数据表展现了 Fuchsia 通过会话框架和驱动框架使产品在核心平台上的定制成为可能。]
数据表显示了 Fuchsia 如何通过会话框架和驱动框架在核心平台上实现产品定制。
感觉这样会比较通顺

2022-08-26 11:29 UTC, XuYicong commented
你好，请修复冲突，否则这边没有办法合并

2022-09-06 06:06 UTC, XuYicong requested changes
你好，请适当修改这个PR，之后才能合并。

2022-10-09 08:42 UTC, wwvm commented on get-started/_common/components/_product_intro.md
> +![数据表展现了 Fuchsia 通过会话框架和驱动框架使产品在核心平台上的定制成为可能。]
```suggestion
![数据表显示了 Fuchsia 如何通过会话框架和驱动框架在核心平台上实现产品定制。]
```

2022-10-09 08:45 UTC, wwvm commented on get-started/_common/components/_product_intro.md
> +组件构成了在 Fuchsia 用户空间中运行的软件的基础。 到目前为止，您所探索的组件是运行 Fuchsia 的所有产品通用的核心平台的一部分。Fuchsia 产品由平台组件和特定于产品的元素组成，以满足设备硬件和用户体验的独特需求。 在本节中，您将探索 Fuchsia 如何构建组件以实现产品级定制。
```suggestion
组件构成了在 Fuchsia 用户空间中运行的软件的基础。 到目前为止，您所探索的组件是运行 Fuchsia 的所有产品通用的核心平台的一部分。Fuchsia 产品由平台组件和特定于产品的元素组成，以满足设备硬件和用户体验的独特需求。在本节中，您将探索 Fuchsia 如何构建组件以实现产品级定制。
```

2023-03-29 13:34 UTC, merged