翻译product session文件
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #186
Opened 2022-08-07 02:32 UTC by wwvm

已经将原来PR中的修改意见合并。

2022-08-08 09:24 UTC, y2-Whyto reviewed
小建议

2022-08-08 09:24 UTC, y2-Whyto commented on get-started/_common/components/_product_session.md
> +会话是一系列封装了产品用户体验的组件。会话框架充当 Fuchsia 平台和产品级用户交互之间的边界。每个 Fuchsia 产品都将单个会话实例定义为产品体验的根，并可能管理其他子组件。
```suggestion
会话是一系列封装了产品用户体验的组件。会话框架充当 Fuchsia 平台和产品级用户之间交流的边界。每个 Fuchsia 产品都将单个会话实例定义为产品体验的根，它可能管理，也可能不管理其他子组件。
```

直接用“并”的话，主语可能有点问题。

2022-08-08 09:24 UTC, y2-Whyto commented on get-started/_common/components/_product_session.md
> +`session_manager` 平台组件在启动时打开会话组件，并为其提供一组固定的功能，以支持诸如窗口管理、输入事件处理或可访问元素的会话框架 API。
```suggestion
`session_manager` 平台组件在启动时打开会话组件，并为其提供一组固定的功能，以支持诸如窗口管理、输入事件处理或无障碍功能等元素的会话框架 API。
```

加入一个“等”，可以避免“元素”跟前面连在一起。

accessibility 根据 Google 公司帮助文档，翻译为“无障碍功能”。参见：
- https://support.google.com/accessibility/android/answer/9078941?hl=zh-Hans
- https://support.google.com/chromebook/answer/177893?hl=zh-Hans

2022-08-08 09:26 UTC, y2-Whyto commented
@Lyrance

2022-08-09 11:28 UTC, y2-Whyto approved these changes, later dismissed

2022-08-09 15:36 UTC, Lyrance requested changes

2022-08-09 15:36 UTC, Lyrance commented on get-started/_common/components/_product_session.md
> +注: 要获取关于会话框架的更多细节，请参阅[会话框架介绍](/concepts/session/introduction.md).
中文句号问题

2022-08-14 04:11 UTC, y2-Whyto commented on get-started/_common/components/_product_session.md
> +注: 要获取关于会话框架的更多细节，请参阅[会话框架介绍](/concepts/session/introduction.md).
```suggestion
注: 要获取关于会话框架的更多细节，请参阅[会话框架介绍](/concepts/session/introduction.md)。
```

2022-08-14 04:13 UTC, y2-Whyto commented
句号问题我已经进行commit了，还有其他问题吗？ @Lyrance

2022-08-14 06:29 UTC, Lyrance commented
> 句号问题我已经进行commit了，还有其他问题吗？ @Lyrance 

没有了

2022-08-14 06:29 UTC, Lyrance approved these changes, later dismissed

2022-08-14 10:45 UTC, y2-Whyto approved these changes, later dismissed

2022-08-14 10:48 UTC, y2-Whyto approved these changes

2022-08-14 10:48 UTC, merged