翻译组件概览
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #187
Opened 2022-08-07 02:42 UTC by wwvm

get-started/_common/components/_overview.md

2022-08-08 09:45 UTC, y2-Whyto commented on get-started/_common/components/_overview.md
> +一个组件是一个运行在 Fuchsia 沙盒中的程序。每个组件都是一个可组合的模块，依据各自功能与其它组件交互。Fuchsia 中所有软件都被定义为组件，除了内核、引导进程以及组件管理器。
```suggestion
组件是 Fuchsia 上运行在其自有沙盒中的程序。每个组件都是一个可组合的模块，通过其能力（capability）与其它组件交互。Fuchsia 中所有软件都被定义为组件，除了内核镜像、引导进程以及组件管理器（Component Manager）。
```

存在漏译的情况。第一句，沙盒应该是组件各自拥有的，而非 Fuchsia 一整个的。

2022-08-08 09:45 UTC, y2-Whyto commented on get-started/_common/components/_overview.md
> +Fuchsia 的组件框架致力于让系统可以运行几乎所有的用户空间软件。组件管理器是一个系统进程，负责协调各个组件实例的执行和生命周期、维护组件拓扑、给组件提供相应功能，并使它们彼此隔离。
```suggestion
Fuchsia 的组件框架负责运行系统内几乎所有的用户空间软件。组件管理器是一个系统进程，它协调各个组件实例的执行和生命周期，维护组件拓扑，给组件提供相应功能，并使它们彼此隔离。
```

2022-08-08 09:45 UTC, y2-Whyto commented on get-started/_common/components/_overview.md
> +组件通过功能获得访问更广泛系统的各个部分的特权。每个组件都可以声明它们提供给系统的新功能以及需要其他组件（或框架）提供的功能。组件管理器解析并验证组件间的所有功能请求，以确保它们与组件已被正确授予的功能相匹配。
```suggestion
组件通过能力来获得访问更广泛系统的各个部分的权限。每个组件都可以声明它们提供给系统的新能力，以及它们运行所需的其他组件（或框架）提供的能力。组件管理器解析并验证组件间的所有能力请求，以确保它们与组件已被正确授予的能力相匹配。
```

2022-08-08 09:45 UTC, y2-Whyto commented on get-started/_common/components/_overview.md
> +<p>本节重点介绍使用组件清单语言 (CML) 编写清单声明的现代组件。此处未介绍基于 <code>appmgr</code> 并使用 CMX 清单声明的旧框架。
```suggestion
<p>本节重点介绍使用组件清单语言 (component manifest language，CML) 编写清单声明的现代组件。此处未介绍基于 <code>appmgr</code> 并使用 CMX 清单声明的旧框架。
```

2022-08-08 09:46 UTC, y2-Whyto commented
@Lyrance

2022-08-09 14:06 UTC, y2-Whyto commented on get-started/_common/components/_overview.md
> +组件通过能力来获得访问更广泛系统的各个部分的权限。每个组件都可以声明它们提供给系统的新能力，以及它们运行所需的其他组件（或框架）提供的能力。组件管理器解析并验证组件间的所有能力请求，以确保它们与组件已被正确授予的能力相匹配。
```suggestion
组件通过能力来获得访问更广泛系统的各个部分的权限。每个组件都可以声明其提供给系统的新能力，以及其运行所需的其他组件（或框架）提供的能力。组件管理器解析并验证组件间的所有能力请求，以确保它们与组件已被正确授予的能力相匹配。
```

这里“每个”用的单数，所以再改一下。

2022-08-26 10:39 UTC, Lyrance submitted a review, later dismissed

2022-08-26 11:39 UTC, XuYicong commented
你好，因为存在冲突，无法合并你的PR。请修复合并冲突，我这边再尝试合并

2022-09-06 06:01 UTC, XuYicong requested changes
你好，请对这个PR做适当更改，然后才能合并。

2022-10-10 02:51 UTC, wwvm commented
我这个需要怎么更改呢？

2022-10-15 06:18 UTC, XuYicong approved these changes

2022-10-15 06:19 UTC, merged