翻译get-started中explore_fuchsia文件
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #189
Opened 2022-08-07 03:37 UTC by wwvm

get-started/explore_fuchsia.md

关于contribute changes已经创建issue供讨论。
文档末尾的reference links相关的信息似乎不用翻译，最后不呈现。

2022-08-08 10:01 UTC, y2-Whyto reviewed
一些建议。

2022-08-08 10:01 UTC, y2-Whyto commented on get-started/explore_fuchsia.md
> +*  [运行示例程序](#run-examples).
```suggestion
*  [运行示例](#run-examples).
```

与 57 行保持一致。

2022-08-08 10:01 UTC, y2-Whyto commented on get-started/explore_fuchsia.md
> +*   [运行样例组件](/development/run/run-examples.md)
```suggestion
*   [运行示例组件](/development/run/run-examples.md)
```

与前文保持一致，example 的翻译不应该反复改变。

2022-08-08 10:01 UTC, y2-Whyto commented on get-started/explore_fuchsia.md
> +Fuchsia 中最小可运行软件单元是[组件](/concepts/components/v2)，这些组件通过
```suggestion
Fuchsia 中软件的最小可执行单元是[组件](/concepts/components/v2)，这些组件通过
```

execute，run；把软件放在前面更通顺一些。

2022-08-08 10:01 UTC, y2-Whyto commented on get-started/explore_fuchsia.md
> +要想了解更多有关 Fuchsia 组件和 FIDL 的信息，参考如下指南：
```suggestion
要想了解更多有关 Fuchsia 组件和 FIDL 的信息，请参考如下指南：
```

2022-08-08 10:01 UTC, y2-Whyto commented on get-started/explore_fuchsia.md
> +*  [贡献修订](#contribute-changes).
```suggestion
*  [贡献更改](#contribute-changes).
```

与 90 行保持一致。

2022-08-08 10:01 UTC, y2-Whyto commented on get-started/explore_fuchsia.md
> +*   [源码规划](/development/source_code/layout.md)
```suggestion
*   [源代码布局](/development/source_code/layout.md)
```

source code 请翻译为源“**代**”码，另外引用的文档是介绍目录结构的，因此翻译为“布局”可能更好。

2022-08-08 10:01 UTC, y2-Whyto commented on get-started/explore_fuchsia.md
> +<!-- [components]: /concepts/components/v2
```suggestion
[components]: /concepts/components/v2
```
请不要翻译超链接的名称，以免影响正文引用它们。下文同。

2022-08-08 10:01 UTC, y2-Whyto commented on get-started/explore_fuchsia.md
> +[贡献更改]: /development/source_code/contribute_changes.md
```suggestion
[contribute-changes]: /development/source_code/contribute_changes.md
```

2022-08-08 10:02 UTC, y2-Whyto commented
@Lyrance

2022-08-09 11:30 UTC, y2-Whyto approved these changes, later dismissed

2022-08-09 15:47 UTC, Lyrance requested changes

2022-08-09 15:47 UTC, Lyrance commented on get-started/explore_fuchsia.md
> +*  [贡献更改](#contribute-changes).
@y2-Whyto 这里的话是用中文标点英文标点或者没有标点会比较好？
我感觉渲染出来的话没有标点比较好看

2022-08-09 15:47 UTC, Lyrance commented on get-started/explore_fuchsia.md
> +在设备或模拟器上启动并运行 Fuchsia 后，请查看以下资源：
都改成参阅吧，这样统一一下，下面还有几个地方也同理

2022-08-10 04:02 UTC, y2-Whyto commented on get-started/explore_fuchsia.md
> +*  [贡献更改](#contribute-changes).
使用中文标点吧。这里可以跟英文保持对应。很细心，我很多这种问题没有检查出来。👍

2022-08-17 08:31 UTC, y2-Whyto commented on get-started/explore_fuchsia.md
> +在设备或模拟器上启动并运行 Fuchsia 后，请查看以下资源：
之前翻译为“参阅”的地方是“see”，这里check out用词不同。我个人感觉使用“查看”是可以的。毕竟用词是“资源”。

2022-08-17 08:31 UTC, y2-Whyto commented on get-started/explore_fuchsia.md
> +*  [贡献更改](#contribute-changes).
```suggestion
*  [运行 ffx 命令](#run-ffx-commands)。
*  [运行示例](#run-examples)。
*  [创建 Fuchsia 组件](#create-fuchsia-components)。
*  [贡献更改](#contribute-changes)。
```

2022-08-17 08:32 UTC, y2-Whyto commented on get-started/explore_fuchsia.md
> +*  [贡献更改](#contribute-changes).
中文标点已经修改了。

2022-08-18 10:11 UTC, Lyrance approved these changes, later dismissed

2022-08-20 08:12 UTC, y2-Whyto commented on get-started/explore_fuchsia.md
> +在设备或模拟器上启动并运行 Fuchsia 后，请查看以下资源：
解决冲突的时候发现 check out 确实上下文翻译不一致。所以全部替换成了“参阅”。

2022-08-20 08:12 UTC, y2-Whyto approved these changes

2022-08-20 08:12 UTC, merged