翻译包简介
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #194
Opened 2022-08-07 04:51 UTC by wwvm

get-started/_common/intro/_packages_intro.md

2022-08-09 16:09 UTC, Lyrance requested changes

2022-08-09 16:09 UTC, Lyrance commented on get-started/_common/intro/_packages_intro.md
> +Fuchsia 软件通过**包****按需**交付到系统中。这是 Fuchsia 的**安全性**和**可更新性**核心设计原则的关键组成部分。包可以单独更新和按需交付，就像网页一样。这使得漏洞补丁可以一次性推送到所有的 Fuchsia 产品中，而无须针对各个产品单独协调。
“包”和“按需”之间不用加*

2022-08-09 16:09 UTC, Lyrance commented on get-started/_common/intro/_packages_intro.md
> +  <p>要学习更多关于哈希根及其在 Fuchsia 中的应用，请参看<a href="/concepts/packages/merkleroot.md">Fuchsia 包哈希</a>。</p>
请参阅

2022-08-09 16:09 UTC, Lyrance commented on get-started/_common/intro/_packages_intro.md
> +* `meta/contents`: 一份人可读文件名与其内容地址的映射。
人可读翻译有点生硬了
可以改为“可供阅读的”
或者还有没有什么别的比较好的翻译

2022-10-09 08:36 UTC, wwvm commented on get-started/_common/intro/_packages_intro.md
> +  <p>要学习更多关于哈希根及其在 Fuchsia 中的应用，请参看<a href="/concepts/packages/merkleroot.md">Fuchsia 包哈希</a>。</p>
```suggestion
  <p>要学习更多关于哈希根及其在 Fuchsia 中的应用，请参阅<a href="/concepts/packages/merkleroot.md">Fuchsia 包哈希</a>。</p>
```

2022-10-09 08:36 UTC, wwvm commented on get-started/_common/intro/_packages_intro.md
> +* `meta/contents`: 一份人可读文件名与其内容地址的映射。
```suggestion
* `meta/contents`: 一份利于人们阅读的文件名与其内容地址的映射。
```

2023-03-29 13:34 UTC, merged