Translated best_practices.md, boards_and_products.md, bringup.md, bundles.md, index.md
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #42
Opened 2021-05-15 02:54 UTC by y2-Whyto

2021-05-15 09:19 UTC, Mr-Linus requested changes

2021-05-15 09:19 UTC, Mr-Linus commented on development/languages/c-cpp/editors.md
> +# C++ Editor/IDE Setup
这个文件是不是被还原了？

2021-05-15 10:30 UTC, y2-Whyto commented on development/languages/c-cpp/editors.md
> +# C++ Editor/IDE Setup
诶？这个文件我似乎没有要动

2021-05-16 09:04 UTC, y2-Whyto commented on development/languages/c-cpp/editors.md
> +# C++ Editor/IDE Setup
啊..我搞懂了，已经撤销撤销了😆

2021-05-16 14:40 UTC, merged