[get-start][目录]翻译初稿
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #43
Opened 2021-05-15 17:58 UTC by Sylsd

@dongchany 

第一次提交翻译pr，不知道 哪种方式更方便review， 目录提交？还是单文件提交？

这次使用了目录，我想这样既能让一次审核的内容更连贯，也避免了大量pr，影响审核效率。

2021-05-15 19:02 UTC, yang-lile approved these changes
总体格式上没有什么问题。

2021-05-16 04:52 UTC, yang-lile requested changes
可能格式上还是有很多问题，建议参考 #37 来学习修改。欢迎多交流单行过长的解决办法。

2021-05-16 04:52 UTC, yang-lile commented on get-started/README.md
```suggestion
```

注释之后还是不要改变原文格式。

2021-05-16 04:52 UTC, yang-lile commented on get-started/README.md
> +   [快速上手 Fuchsia 编译和部署](/docs/development/build/build_and_pave_quickstart.md)。
```suggestion
想在真机上运行 Fuchsia，请参考 [真机安装 Fuchsia](/docs/development/hardware/paving.md) 和 [快速上手 Fuchsia 编译和部署](/docs/development/build/build_and_pave_quickstart.md)。
```

2021-05-16 04:52 UTC, yang-lile commented on get-started/README.md
> +## 为 Zircon 做贡献
```suggestion

## 为 Zircon 做贡献
```

注释段和译文段之间空一行

2021-05-16 04:52 UTC, yang-lile commented on get-started/README.md
> +   [快速上手 Fuchsia 编译和部署](/docs/development/build/build_and_pave_quickstart.md)。
这里其实可以参考 #37 的样式，单过长的情况还是只做保持，不用分行

2021-05-16 13:20 UTC, Sylsd commented on get-started/README.md
> +## 为 Zircon 做贡献
@yang-lile 多谢审核， 我会参照 #37 的样式及上述建议进行更新， 结合一些翻译内容上的错误修复， 再提交一版更新

2021-05-16 15:45 UTC, dongchany commented
> @dongchany
> 
> 第一次提交翻译pr，不知道 哪种方式更方便review， 目录提交？还是单文件提交？
> 
> 这次使用了目录，我想这样既能让一次审核的内容更连贯，也避免了大量pr，影响审核效率。

我个人建议，是每个文件完成后commit 一次， 只要还没有merge 到远程主分支，PR会自动跟上上一次的内容，不会出现大量PR。

2021-05-16 16:44 UTC, Sylsd commented
> > @dongchany
> > 第一次提交翻译pr，不知道 哪种方式更方便review， 目录提交？还是单文件提交？
> > 这次使用了目录，我想这样既能让一次审核的内容更连贯，也避免了大量pr，影响审核效率。
> 
> 我个人建议，是每个文件完成后commit 一次， 只要还没有merge 到远程主分支，PR会自动跟上上一次的内容，不会出现大量PR。

好的，我认为可以将规则设定如下：
1. 以“目录”为单位，一个目录一个PR
2. 提交第一个文件时，创建PR
3. review时，少量问题reviewer直接用GitHub提suggestion；量大或有规律的问题、建议，以Comment形式体现，由作者更正后，集中commit。

2021-05-16 17:00 UTC, Sylsd commented
@yang-lile 上述[问题](https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN/pull/43#pullrequestreview-660406185)已在 7342d28 commit中更正
具体内容：
1. 注释与译文间隔一行，注释标记符号单独一行
2. 清理 多余的空白行、空格
3. 保留部分“单回车”换行，取消review时不方便阅读的断行，合并为一行
4. 其他格式问题

同时修正了部分翻译问题：
1. 将 `build` 翻译成 `构建` （ da80eec 版本中，错误地将其翻译为 编译）
2. 将 `terminal` 统一翻译成 `终端` （da80eec 版本中，直接使用英文单词，未翻译）

遗留的翻译问题：
1. /docs/get-started/build_fuchsia.md 中关于 `board` 和 `product` 由于没有得出明确结论，需要等待其所属章节翻译完成，再跟进修改同步，所属章节为：/docs/concepts/build_system/boards_and_products.md

2021-05-17 05:19 UTC, yang-lile requested changes

2021-05-17 05:19 UTC, yang-lile commented on get-started/_toc.yaml
> +    path: /docs/get-started/explore_fuchsia.md
修改之前是对的，不需要缩减

```yaml
toc:
- title: "概述"
  path: /docs/get-started/README.md
- heading: "Fuchsia 入门"
- title: "获取 Fuchsia 源代码"
  path: /docs/get-started/get_fuchsia_source.md
- title: "构建 Fuchsia"
  path: /docs/get-started/build_fuchsia.md
- title: "配置并运行 Fuchsia 模拟器(FEMU)"
  path: /docs/get-started/set_up_femu.md
- title: "探索 Fuchsia"
  path: /docs/get-started/explore_fuchsia.md
```

2021-05-17 05:19 UTC, yang-lile commented on get-started/_toc.yaml
> +    path: /docs/get-started/explore_fuchsia.md
然后这个_toy文件的语法应该是title对应path里文件里的一级标题。比如：

`get-started/build_fuchsia.md` 文件中的一级标题：
```md
# 配置和构建 Fuchsia {#configure-and-build-fuchsia}
```

修改方法：
```yaml
# - title: "构建 Fuchsia"
- title: "配置和构建 Fuchsia"
  path: /docs/get-started/build_fuchsia.md
```

2021-05-17 10:29 UTC, merged