development/languages/rust/README.md translation
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #71
Opened 2021-06-14 14:27 UTC by chuyao

2021-06-16 16:34 UTC, dongchany reviewed
整体翻译得挺顺的

2021-06-16 16:34 UTC, dongchany commented on development/languages/rust/README.md
>  The `rust_cap_lints` GN arg allows you to control this behavior in your development environment.
这一整段都没了。

2021-06-16 16:34 UTC, dongchany commented on development/languages/rust/crates.md
> +    一个受 BoringSSL 支持的 Rust 加密库
```suggestion
    一个由 BoringSSL 支持的 Rust 加密库
```

2021-06-17 00:45 UTC, chuyao commented on development/languages/rust/README.md
>  The `rust_cap_lints` GN arg allows you to control this behavior in your development environment.
大意了，居然漏掉这么一大段，后继翻译会加强检查，TKS

2021-06-17 00:47 UTC, chuyao commented on development/languages/rust/README.md
>  The `rust_cap_lints` GN arg allows you to control this behavior in your development environment.
> 
> 
> 这一整段都没了。

大意了，居然漏掉这么一大段，后继翻译会加强检查，TKS

2021-06-17 03:03 UTC, merged

2021-06-17 10:24 UTC, yang-lile requested changes
作曲家这个翻译可能需要斟酌一下

2021-06-17 10:24 UTC, yang-lile commented on development/languages/rust/README.md
> +我们的构建配置会默认把所有的 Rust 告警当成错误来处理。这个要求在开发过程中很繁重， 而你希望在你的本地机器上看到的是告警就是告警，从而让 CQ 强制执行硬边界。
```suggestion
我们的构建配置会默认把所有的 Rust 告警当成错误来处理。这个要求在开发过程中很繁重， 而你希望在你的本地机器上看到的是警告就是警告，从而让 CQ 强制执行硬边界。
```

2021-06-17 10:24 UTC, yang-lile commented on development/languages/rust/crates.md
> +    Fuchsia 归档 (FARs)
```suggestion
    使用 Fuchsia 归档 (FARs)
```

2021-06-17 10:24 UTC, yang-lile commented on development/languages/rust/crates.md
> +    Scenic 的 Rust 接口，Fuchsia作曲家
```suggestion
    Fuchsia 合成器 Scenic 的 Rust 接口
```