feat:update structure.md
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #81
Opened 2021-06-20 08:46 UTC by Rocksnake

完成 /development/languages/new/structure.md 的翻译

2021-06-21 04:45 UTC, yang-lile requested changes
还有一些中英文括号的问题就不做备注了，希望修改一下规范一点。

2021-06-21 04:45 UTC, yang-lile commented on development/languages/new/structure.md
> +Fuchsia 底层支持允许 [Zircon 系统调用](/docs/reference/syscalls/)的语言，用这种语言编写的程序依赖于开放性的系统调用可以与内核交互，以及和系统其余结构 ( 除内核以外 ) 互相传递信息。
```suggestion
Fuchsia 底层支持允许 [Zircon 系统调用](/docs/reference/syscalls/)的语言，用这种语言编写的程序依赖于开放性的系统调用可以与内核交互，以及和系统其余结构互相传递信息。
```

其实还是可以理解出这个意思的，就不需要在补充了。

2021-06-21 04:45 UTC, yang-lile commented on development/languages/new/structure.md
> +从另一个线程唤醒当前线程不需要额外的内核对象。您可以通过 [zx_port_queue](https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN/blob/2021/docs/reference/syscalls/port_queue.md) 简要地为线程端口排列用户包信息来唤醒线程。
```suggestion
绝大多数 Fuchsia 中的程序充当着 *服务者* 的角色。开始运行后，这些程序会在消息线程中不断循环以接受消息，处理消息（可能发送消息到其他进程），然后该进程进入休眠状态。

Fuchsia 中的消息线程最基础的组成结构是 [端口](https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN/blob/2021/docs/reference/kernel_objects/port.md) ，线程可以通过  [`zx_port_wait`](https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN/blob/2021/docs/reference/syscalls/port_wait.md) 进入休眠状态，当内核唤醒线程时，会发送一个数据包给到线程，这个数据包描述了内核唤醒线程的原因。

通常，每个线程进入休眠状态时都会有一个单独的端口，当您使用您熟悉的编程语言编写大量代码时就会与之交互。语言维护者（运营者）通常会提供抽象化端口和异步等待的库，而不是直接开放接口。

大多数异步等待操作都在  [`zx_object_wait_async`](https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN/blob/2021/docs/reference/syscalls/object_wait_async.md) 中，通常，`port` 和 `key` 两个参数由库提供，`handle` 和 `signals` 两个参数由客户端提供。 当一个等待操作被创建，客户端通常还会提供一个向上调用（例如，一个闭包）供库在等待完成时调用，此时库会通过 `key` 参数恢复向上调用（例如，从一个散列表中）。

从另一个线程唤醒当前线程不需要额外的内核对象。您可以通过 [zx_port_queue](https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN/blob/2021/docs/reference/syscalls/port_queue.md) 简要地为线程端口排列用户包信息来唤醒线程。
```

翻译之后保持语言和符号的统一会更好一些。

修改了一句带括号的翻译。

2021-06-21 04:45 UTC, yang-lile commented on development/languages/new/structure.md
> +- 一种编解码器，它可以将这些数据结构序列化 / 反序列化成 [FIDL wire format](https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN/blob/2021/docs/reference/fidl/language/wire-format) （FIDL 线型结构）格式或逆转换
```suggestion
- 一种编解码器，它可以将这些数据结构序列化/反序列化成 [FIDL wire format](https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN/blob/2021/docs/reference/fidl/language/wire-format) （FIDL 线型结构）格式或逆转换
```

2021-06-21 23:51 UTC, Rocksnake commented on development/languages/new/structure.md
> +- 一种编解码器，它可以将这些数据结构序列化 / 反序列化成 [FIDL wire format](https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN/blob/2021/docs/reference/fidl/language/wire-format) （FIDL 线型结构）格式或逆转换
好的，我已经按照规范修改完成，之后会注意的

2021-06-22 11:32 UTC, yang-lile requested changes
麻烦再做最后的一点修改吧，已经很不错了

2021-06-22 11:32 UTC, yang-lile commented on development/languages/new/structure.md
> +-  [zxwait](https://fuchsia.googlesource.com/third_party/go/+/HEAD/src/syscall/zx/zxwait/) (Go )
```suggestion
* [异步](/zircon/system/ulib/async) (C 和 C++)
* [Fuchsia 异步](/src/lib/fuchsia-async/) (Rust)
* [zxwait](https://fuchsia.googlesource.com/third_party/go/+/HEAD/src/syscall/zx/zxwait/) (Go)
```

c 和 c++这个如果单独放一段落可能会格式出错，建议和上一段贴近

2021-06-22 11:32 UTC, yang-lile commented on development/languages/new/structure.md
> +- 用目标语言编写的支持库，供第一部分生成的代码使用
```suggestion
1. 用于目标语言代码生成的 FIDL 编译器的特定语言后端
2. 用目标语言编写的支持库，供第一部分生成的代码使用
```

序号问题

2021-06-23 02:25 UTC, Rocksnake commented on development/languages/new/structure.md
> +- 用目标语言编写的支持库，供第一部分生成的代码使用
好的👌

2021-06-28 04:46 UTC, yang-lile approved these changes

2021-06-28 04:46 UTC, merged