翻译了四个文件，请检查
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #95
Opened 2021-07-08 06:01 UTC by yang-lile

2021-07-09 02:20 UTC, chuyao approved these changes
good

2021-07-09 02:46 UTC, chuyao requested changes
`Note` , `Package` 的翻译可以讨论一下

2021-07-09 02:46 UTC, chuyao commented on development/languages/dart/README.md
> +Note: 从 dart:io 调用 exit() 将导致异常，因为不允许组件调用此方法，因为它将关闭 dart_runner 进程。
`Note` 我觉得可以翻译一下

2021-07-09 02:46 UTC, chuyao commented on development/languages/dart/README.md
> +## Package 结构 {#layout}
全部翻译是否更好些？ `包结构`

2021-07-09 02:46 UTC, chuyao commented on development/languages/dart/README.md
> +## Package 结构 {#layout}
全部翻译是否更好些？ `包结构`

2021-07-11 12:12 UTC, y2-Whyto requested changes

2021-07-11 12:12 UTC, y2-Whyto commented on development/languages/dart/README.md
> +这是为了确保我们在多个版本中使用一致的依赖版本。
```suggestion
这是为了确保我们在多个构建中使用一致的依赖版本。
```
如果粗略地将 build 和 version 都翻译成“版本”的话，可能会引起读者的困惑。

2021-07-11 12:12 UTC, y2-Whyto commented on development/languages/dart/README.md
> +Fuchsia 的 Dart 运行程序不会监视 Dart 程序打开的 FIDL 通道，因此不会正常结束该程序，而是等待对 `fuchsia.exit()` 的显示调用以指示该程序应该结束。
```suggestion
Fuchsia 的 Dart 运行程序不会监视 Dart 程序打开的 FIDL 通道，因此不会正常结束该程序，而是等待对 `fuchsia.exit()` 的显式调用以指示该程序应该结束。
```
显“式”，错别字。

2021-07-11 12:12 UTC, y2-Whyto commented on development/languages/dart/README.md
> +- [`dart_library`][target-library] 定义了能够被用户使用的 Dart 库；
```suggestion
- [`dart_library`][target-library] 定义了一个能够被其他 Dart 目标使用的库；
```
是不是翻译串了？

2021-07-11 12:12 UTC, y2-Whyto commented on development/languages/dart/README.md
> +  |-- pubspec.yaml           # 空的，用来做标记 [必要的]
```suggestion
  |-- pubspec.yaml           # 空的，用来做标记【必需】
```
建议用“必需”代替“必要的”，这样看起来可能更书面一些。

2021-07-11 12:12 UTC, y2-Whyto commented on development/languages/dart/README.md
> +- [运行时分析](analysis.md)
```suggestion
- [运行分析](analysis.md)
```
“运行”分析还是“运行时”分析？运行时好像是指运行环境和依赖吧，二者似乎不太一样。

2021-07-11 12:12 UTC, y2-Whyto commented on development/languages/dart/analysis.md
> +分析是运行 Fuchsia 构建的一部分。
```suggestion
分析作为 Fuchsia 构建的一部分运行。
```

2021-07-11 12:12 UTC, y2-Whyto commented on development/languages/dart/analysis.md
> +分析是运行 Fuchsia 构建的一部分。
```suggestion
分析的运行是 Fuchsia 构建的一部分。
```

2021-07-11 12:12 UTC, y2-Whyto commented on development/languages/dart/analysis.md
> +分析是运行 Fuchsia 构建的一部分。
上述两种翻译对于原文含义的保留可能更好些？原翻译把“运行”的宾语更换了，对比原文看起来怪怪的。

2021-07-11 12:12 UTC, y2-Whyto commented on development/languages/dart/analysis.md
> +对于每一个 `dart_library` 目标，分析脚本会获取并生成到输出目录下：
```suggestion
对于每一个 `dart_library` 目标，分析脚本也会生成到位于下面路径中的输出路径下：
```
gets generated == is generated
（应该吧）

所以没有“获取”。

2021-07-11 14:12 UTC, yang-lile commented on development/languages/dart/README.md
> +Note: 从 dart:io 调用 exit() 将导致异常，因为不允许组件调用此方法，因为它将关闭 dart_runner 进程。
我是担心破坏原文的Note样式，所以一直没有翻译Note。这个可以提一个issue讨论一下？

2021-07-11 14:12 UTC, yang-lile commented on development/languages/dart/README.md
> +## Package 结构 {#layout}
好的

2021-07-11 14:13 UTC, yang-lile commented on development/languages/dart/README.md
> +这是为了确保我们在多个版本中使用一致的依赖版本。
明白了，下次会注意

2021-07-11 14:15 UTC, yang-lile commented on development/languages/dart/README.md
> +Fuchsia 的 Dart 运行程序不会监视 Dart 程序打开的 FIDL 通道，因此不会正常结束该程序，而是等待对 `fuchsia.exit()` 的显示调用以指示该程序应该结束。
粗心了，谢谢提醒

2021-07-11 14:15 UTC, yang-lile commented on development/languages/dart/README.md
> +Fuchsia 的 Dart 运行程序不会监视 Dart 程序打开的 FIDL 通道，因此不会正常结束该程序，而是等待对 `fuchsia.exit()` 的显示调用以指示该程序应该结束。
粗心了，谢谢提醒

2021-07-11 14:17 UTC, yang-lile commented on development/languages/dart/README.md
> +  |-- pubspec.yaml           # 空的，用来做标记 [必要的]
学会了，谢谢

2021-07-11 14:19 UTC, yang-lile commented on development/languages/dart/README.md
> +- [`dart_library`][target-library] 定义了能够被用户使用的 Dart 库；
确实是我的问题

2021-07-11 14:31 UTC, yang-lile commented on development/languages/dart/README.md
> +- [运行时分析](analysis.md)
检查了一下原文大意，确实是运行分析

2021-07-11 14:32 UTC, yang-lile commented on development/languages/dart/analysis.md
> +分析是运行 Fuchsia 构建的一部分。
傻了，这个可能是没睡醒翻译的

2021-07-11 14:37 UTC, yang-lile commented on development/languages/dart/analysis.md
> +分析是运行 Fuchsia 构建的一部分。
这里应该是指分析的运行，是构建的一部分，同意你的观点

2021-07-11 14:39 UTC, yang-lile commented on development/languages/dart/analysis.md
> +对于每一个 `dart_library` 目标，分析脚本会获取并生成到输出目录下：
自信一点，就是被动句，我给直译了

2021-07-11 14:43 UTC, yang-lile commented on development/languages/dart/README.md
> +## Package 结构 {#layout}
已经解决

2021-07-11 14:56 UTC, chuyao submitted a review, later dismissed

2021-07-11 23:57 UTC, y2-Whyto requested changes

2021-07-11 23:57 UTC, y2-Whyto commented on development/languages/dart/README.md
>    |-- analysis_options.yaml  # 分析配置项 [必要的]
```suggestion
  |-- analysis_options.yaml  # 分析配置项【必需】
```
这里别忘了改😂

2021-07-12 05:32 UTC, yang-lile commented
修改完成，麻烦同意pr，谢谢 @chuyao @y2-Whyto

2021-07-12 05:54 UTC, y2-Whyto requested changes
本次核阅包含不少细节，供您参考，劳烦您稍费时间略做检查。

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/analysis.md
> +与标准 Dart Packages 一样，分析选项在 `analysis_options.yaml` 文件中定义，该文件必须放在 package 根目录下。
```suggestion
与标准 Dart 包一样，分析选项在 `analysis_options.yaml` 文件中定义，该文件必须放在包的根目录下。
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/analysis.md
> +通常只包含本地选项文件中的设置：
```suggestion
通常只在本地选项文件中的包含该集合：
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/analysis.md
> +也可以通过传递常规分析器标志：
```suggestion
也可以传递常规分析器标志：
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/fidl.md
> +[FIDL 目标][fidl] 生成隐式 Dart 绑定目标。生成的绑定使用方法：
```suggestion
[FIDL 目标][fidl] 生成隐式 Dart 绑定目标。要使用为下列对象生成的绑定：
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/fidl.md
> +在 BUILD.gn 中添加依赖：
```suggestion
请在 BUILD.gn 中添加依赖：
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/fidl.md
> +* 根据 Dart 包使用的 *另一个* FIDL 目标中的这些目标之一，会导致“无法读取 Dart 源……”错误。
```suggestion
* 对于 Dart 包使用的 *另一* FIDL 目标中的这些目标之一的依赖，会导致“无法读取 Dart 源……”错误。
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/fidl.md
> +  FIDL 的绑定生成器基于包含包含的 FIDL 文件的目录结构构建 Dart 包名称，而 GN（用于计算 Dart 包的依赖关系）使用完整的 GN 目标名称来实现。
```suggestion
  FIDL 的绑定生成器基于含有被包含 FIDL 文件的目录结构来构建 Dart 包名称，而 GN（用于计算 Dart 包的依赖关系）使用完整的 GN 目标名称来实现。
```
这样可能会更清晰一些？起码别出现两个“包含”放在一起的情况吧，有点绕..

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/fidl.md
> +  例如：依赖于 `lib/foo/fidl:bar` 生成一个像 `lib.foo.fidl._bar` 这样的包。
```suggestion
  例如：对 `lib/foo/fidl:bar` 的依赖会生成一个形如 `lib.foo.fidl._bar` 的包。
```
这样写谓语会更清晰一些。

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/fidl.md
> +  根据顶级目标 `lib/foo/fidl` 生成包 `lib.foo.fidl`，这与 Dart FIDL 绑定的假设一致。
```suggestion
  对顶层目标 `lib/foo/fidl` 的依赖会生成包 `lib.foo.fidl`，这与 Dart FIDL 绑定的假设相符。
```
同上。

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/fidl.md
> +FIDL 为 dart 生成了 3 个文件。你可以在 `out/default/dartlang/gen/<path-to-target>/<fidl-servicename>_package/lib` 找到。
```suggestion
FIDL 为 dart 生成了 3 个文件。您可以在 `out/default/dartlang/gen/<path-to-target>/<fidl-servicename>_package/lib` 找到。
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +# Fuchsia 中的 Dart IDEs
```suggestion
# Fuchsia 中的 Dart IDE
```
中文似乎没有保留英文复数的习惯。

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +预构建的 Dart SDK 可用于 IDE 使用：`prebuilt/third_party/dart/{linux|mac|windows}-x64/bin/dart`。
```suggestion
一个预构建的可供 IDE 使用的 Dart SDK 位于：`prebuilt/third_party/dart/{linux|mac|windows}-x64/bin/dart`。
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +        支持 Dart 的编程语法，它将会自动的在 Fuchsia 树中查找到 dart-sdk。
```suggestion
        提供 Dart 编程支持。它会在 Fuchsia 树中自动找到 dart-sdk。
```
支持（support）是中心词。顺便，要用“de”的话要用土也地（）

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +        支持 Fuchsia 的 FIDL 文件的语法高亮。
```suggestion
        提供 Fuchsia 的 FIDL 文件语法高亮支持
```
同上。

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +        GN 构建文件的语法高亮
```suggestion
        GN 构建文件的语法高亮支持
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +            查看 git 日志，文件历史，或者其他
```suggestion
            查看 git 日志、文件历史等
```
这样相对书面一些。

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +    1. 打开你的用户设置 (Ctrl+,)
```suggestion
    1. 打开您的用户设置 (Ctrl+,)
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +    增加设置：
```suggestion
    要增加设置：
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +    3. 添加:
```suggestion
    3. 添加：
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +Note: 配置文件是一个 JSON 文件。请确保你正确的使用了花括号。
```suggestion
Note: 该配置文件是一个 JSON 文件。请确保您正确的使用了花括号。
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +* 当你保存的时候自动格式化你的文件：
```suggestion
* 在您保存时自动格式化您的文件：
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +* 配置 VS Code 使用绑定的 Dart SDK：
```suggestion
* 配置 VS Code 使用 Dart SDK 套装：
```
bundle 一词我在 `/concepts/build_system/bundles.md` 中使用了“套装”的翻译，望您参考。bundle是成捆物品的意思，使用“绑定的”似乎会引起歧义。

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +Note: 对于 macOS，在你的 `dart.sdkPath` 提供值中使用 `mac-x64` 替换 `linux-x64`。
```suggestion
Note: 对于 macOS，请在您的 `dart.sdkPath` 提供值中使用 `mac-x64` 替换 `linux-x64`。
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +* 配置单行上限为 80 个字符宽以及 tab 的宽为 2 个空格
```suggestion
* 配置单行宽度上限为 80 个字符，tab 宽度为 2 个空格
```
润色。

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +* 通过转到 `Settings > Plugins` 然后搜索 Dart 语言支持来添加 Dart 插件。
```suggestion
* 通过转到 `Settings（设置）> Plugins（插件）` 然后搜索 Dart language support（Dart 语言支持）来添加 Dart 插件。
```
这样写更全面？后边的名称应该要保留原文。

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +* 设置 Dart 路径在 `Settings > Languages & Frameworks > Dart` 通过以下步骤：
```suggestion
* 在 `Settings（设置）> Languages & Frameworks（语言和框架） > Dart` 中通过以下步骤设置 Dart 路径：
```
语序？（震惊）

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +如果您发现 IDE 无法在您的 BUILD.gn 依赖项中找到已经正确的导入（红色波浪线），这通常表明 Dart 分析在您的 IDE 中无法正常工作。
```suggestion
如果您发现 IDE 无法在您的 BUILD.gn 依赖项中找到已经正确的导入（红色波浪线），这通常表明 Dart 分析未在您的 IDE 中正常工作。
```
“无法”有点在这儿好像有点 can't 的意味了，用不/未/没能这样的说法可能更好一些？

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +例如：只打开 `/topaz/shell/ermine` 来代替 `/topaz`。分析器在处理非常大的源码树时可能会出问题。
```suggestion
例如：只打开 `/topaz/shell/ermine` 而不是 `/topaz`。分析器在处理非常大的源码树时可能会出问题。
```
“来代替”的话，最前面可能需要加个“用”，这里还得是“用……的方式来代替”。所以还不如用“而不是/而非”翻译着顺当。

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +1. 在你的项目中删除 `.packages` 和 `pubspec.lock` 文件（如果存在的话）；
```suggestion
1. 在您的项目中删除 `.packages` 和 `pubspec.lock` 文件（如果存在的话）；
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +1. 确保在你的 VS Code 首选项中存在 `"dart.runPubGetOnPubspecChanges": false,` 以防止文件再次出现，无论 `pubspec.yaml` 文件何时被编辑；
```suggestion
1. 确保在你的 VS Code 首选项中存在 `"dart.runPubGetOnPubspecChanges": false,` 以防止`pubspec.yaml` 文件改动后前述文件再次出现；
```
润色。

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +   2. 选择 "Reload Window"
```suggestion
   2. 选择“Reload Window（重新加载窗口）”
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +### 确保你的构建包含了所有的包
```suggestion
### 确保您的构建包含了所有的包
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +分析器将无法使用未包含在您的构建中的包中的任何 Dart 代码，所以确保你的构建配置 (`fx set`) 包含你需要的所有包（`--with` 标志可能会有所帮助。）
```suggestion
分析器将无法使用任何未包含在您的构建中的包中的 Dart 代码，所以请确保您的构建配置 (`fx set`) 包含您需要的所有包（`--with` 标志可能会有所帮助。）
```
稍微调整了一下语序。

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +举个例子：要在 VS Code 中查看 `echo_client_async` 示例的 Dart 代码，请将 `--with examples/fidl/dart/echo_client_async_dart` 添加到你的 `fx set` 命令之后。然后，使用 `fx build examples/fidl/dart/echo_client_async_dart` 重建。
```suggestion
举个例子：要在 VS Code 中查看 `echo_client_async` 示例的 Dart 代码，请将 `--with examples/fidl/dart/echo_client_async_dart` 添加到您的 `fx set` 命令之后。然后，使用 `fx build examples/fidl/dart/echo_client_async_dart` 重构建。
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +1.  输入并选择 "Reload Window"
```suggestion
1.  输入并选择“Reload Window（重新加载窗口）”
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +1.  输入并选择 "Restart Dart Analysis Server"
```suggestion
1.  输入并选择“Restart Dart Analysis Server”
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +  * 输入 Dart SDK 路径 "${FUCHSIA_SRC}/third_party/dart/tools/sdks/dart-sdk"
```suggestion
  * 输入 Dart SDK 路径“${FUCHSIA_SRC}/third_party/dart/tools/sdks/dart-sdk”
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +1.  在 VS Code 上使用 Ctrl+Shift+P 然后输入 "Change Language Mode" 并确保它设置为 "Auto Detect"。
```suggestion
1.  在 VS Code 上使用 Ctrl+Shift+P 然后输入“Change Language Mode（更改语言模式）”并确保它设置为“Auto Detect”。
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/ides.md
> +1.  在 *Languages & Frameworks* > *Dart* 下面，输入 "[YOUR FUCHSIA DIR LOCATION]/prebuilt/third_party/dart/{mac,linux}-x64"
```suggestion
1.  在 *Languages & Frameworks*（语言和框架）> *Dart* 下面，输入 "[YOUR FUCHSIA DIR LOCATION]/prebuilt/third_party/dart/{mac,linux}-x64"
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/logging.md
> +在 Fuchsia 上的 Dart 程序通常使用 `lib.logging` 包来写入日志消息，通过 `fuchsia_logger` 包对其进行消费和初始化。
```suggestion
在 Fuchsia 上的 Dart 程序通常使用 `lib.logging` 包来写入日志消息，通过 `fuchsia_logger` 包来获取和初始化。
```
我在 `/concepts/diagnostics` 中使用“获取”来翻译 consume，供您参考。我的考虑是 consume 应该是指“得到并使用”的意思。不知您有何想法？

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/logging.md
> +请参阅 [语言无关日志文档] 来获取更多关于记录和查看日志的信息。
```suggestion
请参阅[语言无关日志文档]来获取更多关于记录和查看日志的信息。
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/logging.md
> +请参阅 [Dart: 概述][dart-dev] 以便了解更多有关于在 Fuchsia 中构建 Dart。
```suggestion
请参阅 [Dart: 概述][dart-dev]以了解关于在 Fuchsia 中构建 Dart 的更多信息。
```
缺宾语。

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/logging.md
> +通过在组件清单中包含以下内容，确保您的组件具有记录所需的功能
```suggestion
请在组件清单中包含以下内容，以确保您的组件具有记录日志所需的功能：
```
这样拆开更通顺一些？

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/logging.md
> +在你的主函数中，调用 `setupLogger()` 函数来初始化日志。
```suggestion
在您的主函数中，调用 `setupLogger()` 函数来初始化日志。
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/logging.md
>  ### Configure severity
```suggestion
<!-- ### Configure severity -->
```

2021-07-12 05:54 UTC, y2-Whyto commented on development/languages/dart/logging.md
> +可以通过在 `setupLogger()` 调用中提供 `level` 参数来调整严重性级别。
```suggestion
可以通过在 `setupLogger()` 调用中给出 `level` 参数来调整严重性级别。
```

2021-07-18 07:18 UTC, yang-lile commented on development/languages/dart/ides.md
> +# Fuchsia 中的 Dart IDEs
确实，总不可能后面加个“们”

2021-07-18 07:26 UTC, yang-lile commented on development/languages/dart/ides.md
> +* 配置 VS Code 使用绑定的 Dart SDK：
那就按您的方式统一起来。

2021-07-18 07:27 UTC, yang-lile commented on development/languages/dart/ides.md
> +* 通过转到 `Settings > Plugins` 然后搜索 Dart 语言支持来添加 Dart 插件。
明白了。

2021-07-18 07:28 UTC, yang-lile commented on development/languages/dart/ides.md
> +* 设置 Dart 路径在 `Settings > Languages & Frameworks > Dart` 通过以下步骤：
翻译翻麻了，中英语序混乱了

2021-07-18 07:55 UTC, yang-lile commented on development/languages/dart/logging.md
> +在 Fuchsia 上的 Dart 程序通常使用 `lib.logging` 包来写入日志消息，通过 `fuchsia_logger` 包对其进行消费和初始化。
只要约定好就行吧，我当时也思考了很久，实在是不明白这个词怎么翻译好

2021-07-18 08:02 UTC, yang-lile commented on development/languages/dart/logging.md
> +可以通过在 `setupLogger()` 调用中提供 `level` 参数来调整严重性级别。
有道词典中找到一个“规定”，您觉得会不会更好一些

2021-07-18 08:07 UTC, yang-lile reviewed
抱歉，最近忙一些事，导致这个pr又搁置了一个星期，现在继续开始吧。

2021-07-18 08:37 UTC, y2-Whyto commented on development/languages/dart/logging.md
> +可以通过在 `setupLogger()` 调用中提供 `level` 参数来调整严重性级别。
查询了英文词典，“规定”义项用在法律中，后接从句，这里应该还是“提供”的意思，我提出“给出”的翻译，只是将“提供”这一释义变成更加口语或者某种程度上更加常用的说法，而不改变本意。仅是参考。

2021-07-18 08:38 UTC, y2-Whyto approved these changes, later dismissed

2021-07-18 10:42 UTC, dongchany commented
> `Note` , `Package` 的翻译可以讨论一下

Note翻译为“说明”，应该可以。

2021-07-20 06:43 UTC, merged