Translated 2 pictures.
FuchsiaOS/FuchsiaOS-docs-zh_CN pull request #98
Opened 2021-07-11 09:24 UTC by y2-Whyto

2021-07-16 02:26 UTC, chuyao commented on concepts/emulator/index.md
>  fx vdl start --help
这段在注释似乎被拿掉了，看了原文才知道有这段，不过无伤大雅了

2021-07-16 02:42 UTC, chuyao requested changes
一些小问题，希望可以修改一下

2021-07-16 02:42 UTC, chuyao commented on concepts/emulator/index.md
> +要配置这些特性，请查看[配置并运行 Fuchsia 模拟器](/docs/get-started/set_up_femu.md)页面。
`start` 翻译为 `启动` 可能要好一点

2021-07-16 02:42 UTC, chuyao commented on concepts/internationalization/_toc.yaml
>    path: /docs/concepts/internationalization/introduction.md
这个 `/docs` 要拿掉，否则提交的链接会 404，参考 #73 及 tg 群过往的讨论

2021-07-16 02:42 UTC, chuyao commented on concepts/internationalization/introduction.md
>  <!--xrefs-->
同上面的 `/docs` 问题

2021-07-16 05:57 UTC, y2-Whyto commented on concepts/internationalization/introduction.md
>  <!--xrefs-->
已经修改，感谢提醒

2021-07-16 05:57 UTC, y2-Whyto commented on concepts/internationalization/introduction.md
>  <!--xrefs-->
已经修改，感谢提醒

2021-07-16 05:59 UTC, y2-Whyto commented on concepts/emulator/index.md
>  fx vdl start --help
没明白您的意思？

2021-07-16 06:00 UTC, y2-Whyto commented on concepts/emulator/index.md
> +要配置这些特性，请查看[配置并运行 Fuchsia 模拟器](/docs/get-started/set_up_femu.md)页面。
已经修改，感谢提醒

2021-07-16 06:01 UTC, y2-Whyto commented on concepts/internationalization/_toc.yaml
>    path: /docs/concepts/internationalization/introduction.md
已更正，感谢提醒

2021-07-17 04:30 UTC, chuyao commented on concepts/emulator/index.md
>  fx vdl start --help
就是你的 <!-- --> 注释块中没有把这段包含进来，而是直接当成了翻译后的内容

2021-07-17 04:32 UTC, chuyao approved these changes

2021-07-17 04:32 UTC, chuyao approved these changes

2021-07-17 04:45 UTC, chuyao approved these changes
go

2021-07-17 04:49 UTC, chuyao approved these changes

2021-07-17 04:52 UTC, chuyao commented
sorry，我的 review 权限似乎不够，不能帮你 merge 了，尝试了几次，有一些多余的信息，抱歉

2021-07-18 08:41 UTC, y2-Whyto commented
> sorry，我的 review 权限似乎不够，不能帮你 merge 了，尝试了几次，有一些多余的信息，抱歉

没事，您可以跟 @dongchany 商量一下权限的事。

2021-07-18 08:44 UTC, yang-lile approved these changes

2021-07-18 08:45 UTC, merged

2021-07-18 09:57 UTC, dongchany commented
> sorry，我的 review 权限似乎不够，不能帮你 merge 了，尝试了几次，有一些多余的信息，抱歉

抱歉，我迟延了。权限已修改好了，放心 merge 吧。